### ISSUE TITLE
#\" breaks highlighting

### ISSUE THREAD

**Issue by samth** [greghendershott/racket-mode#464] opened 2020-05-05 13:58 UTC
```
     (or (equal? #\" (cadr l)) ; #\" ;; fix racket mode syntax highlighting 
```

**Comment by greghendershott** [comment] 2020-05-06 13:43
Thank you for reporting. AFAICT this is a duplicate of #463 so I will close this and work off that.

**Closed by greghendershott** 2020-05-06 13:43 UTC
