### ISSUE TITLE
errors in `with-output-to-string` are silently ignored

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#577] opened 2021-11-14 16:40 UTC
<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "27.2")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/")
 (racket--rkt-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function identity)
 (racket-path-from-racket-to-emacs-function identity)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function racket-repl-buffer-name-project)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-echo-area)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (column-number-mode)
 (company-mode)
 (dumb-jump-mode)
 (electric-indent-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (flycheck-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-undo-tree-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (ido-ubiquitous-mode)
 (ido-vertical-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (menu-bar-mode)
 (override-global-mode)
 (paredit-mode)
 (projectile-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode)
 (undo-tree-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (flyspell-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-dired-hide-details-mode)
 (global-flycheck-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-message-citation-mode)
 (gnus-undo-mode)
 (gud-tooltip-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (image-dired-minor-mode)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (macrostep-mode)
 (mail-abbrevs-mode)
 (minibuffer-electric-default-mode)
 (mml-mode)
 (mouse-wheel-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-smart-open-bracket-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (slime-autodoc-mode)
 (slime-edit-value-mode)
 (slime-editing-mode)
 (slime-fuzzy-target-buffer-completions-mode)
 (slime-macroexpansion-minor-mode)
 (slime-mode)
 (slime-popup-buffer-mode)
 (slime-repl-map-mode)
 (slime-repl-read-mode)
 (slime-trace-dialog-autofollow-mode)
 (slime-trace-dialog-hide-details-mode)
 (slime-trace-dialog-minor-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

Given this module:

```racket
#lang racket/base

(require (for-syntax racket/base
                     racket/port))

(provide
 example)

(define-syntax (example stx)
  (syntax-case stx ()
    [(_)
     (with-syntax ([ok (datum->syntax stx (with-output-to-string
                                            (lambda ()
                                              (error 'fail))))])
       #'ok)]))
```

When I load it into the racket-mode REPL and try to eval `(example)`, the error is ignored. A simplified example like

```racket
(define-syntax (example stx)
  (syntax-case stx ()
    [(_)
     (error 'fail)]))
```

works (fails) as expected. As does, surprisingly, this one:

```racket
(define-syntax (example stx)
  (syntax-case stx ()
    [(_)
     (with-syntax ([ok (datum->syntax stx (call-with-output-string
                                            (lambda (out)
                                              (error 'fail))))])
       #'ok)]))
```

It's entirely possible that I'm being stupid and missing something obvious here.

**Comment by capfredf** [comment] 2021-11-14 19:59
A minimal example to reproduce the issue:
1. open a Racket-Repl
2. run `(with-output-to-string (lambda () (eprintf "hi ...~n") (error "hi")))` at the repl

**Comment by greghendershott** [comment] 2021-12-23 14:43
I'm sorry to be slow to look at this! I got tunnel-visioned on the `hash-lang` branch.

What's happening here is that Racket Mode, much like Dr Racket, installs its own `error-display-handler` (to do things like fully-qualify paths in errors, trim the reported exception "stack" to the user program portion, and so on).

Also (but unlike GUI Dr Racket), when it comes time to display error information, it uses `current-output-port` not `current-error-port`. It does so because eventually these get merged, anyway, because the I/O is done over a TCP connection (with one, meged "O") and furthermore Emacs comint buffers handle stdout/stderr from a process as one merged thing. Also there is some "write a newline but only if not already in the first column" handling which is a lot easier to do correctly with a single output port. Yada yada.

I think all that is fine. However, TL;DR the error display handler should capture the "true"/original `current-output-port` and write stuff _there_. That way, it won't be subject to user programs parameterizing `current-output-port` to something else. As is the case with these example programs.

I have a tentative commit for this; I want to double-check it but will aim to push and merge today.

**Closed** 2021-12-23 15:58 UTC
Labels: bug
