### ISSUE TITLE
cannot run programs requiring racket/gui/base on windows

### ISSUE THREAD

**Issue by vityou** [greghendershott/racket-mode#301] opened 2018-05-09 22:59 UTC
Upon pressing f5, the repl opens, prints "on-demand one-time instantiation of racket/gui/base", and doesn't ever run the program.  This only happens with programs which require gui.

**Comment by greghendershott** [comment] 2018-05-11 04:12
Thanks for the additional information!

This may take me awhile to figure out what's going on. Also, I don't have a Windows laptop with me now; I will toward the end of next week.

Maybe I should make a VirtualBox VM for situations like this, and buy a Windows license.

**Comment by greghendershott** [comment] 2018-05-12 01:03
OK I installed VirtualBox, downloaded and installed [this free Windows VM from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), installed Emacs for Windows and Racket for Windows.

I've never used `2htdp/universe` and `big-bang`. Can you give me an example program that shows the problem?

**Comment by vityou** [comment] 2018-05-12 01:32
Here is a simple program that uses `big-bang`:

#lang racket

(require 2htdp/image)
(require 2htdp/universe)

```
(big-bang 1
  [to-draw (lambda (x) (underlay/xy (rectangle 100 100 "solid" "white") 50 50 (square x 'solid "red")))]
  [on-tick add1]
  [stop-when (lambda (x) (> x 50))])
```

It pretty much passes state between functions and draws something using the `to-draw` function every tick.  When it is finished, (when the `stop-when` function returns true), the `big-bang` function returns the final state, in this case `51`.  What I noticed happening, is that the execution of the program will finish, and the function will return 51.  However, no graphics will be displayed.  Then, when you run it again, the graphics work.  When I was running the program which first caused the issue, it seemed to freeze, because my `big-bang` needs input from the user in order to end, so racket-mode thought that my `big-bang` was running and it just waited for it to stop.

**Comment by greghendershott** [comment] 2018-05-14 12:46
@alex-hhh Thanks for joining in.

When racket-mode prints:

```racket
; on-demand one-time instantiation of racket/gui/base"
```

Do you suppose it should also print something like:

```racket
; TIP: If your frame% window doesn't appear, try entering (send frame show #t).
```

@alex-hhh: What do you think?
@vityou: Would that have helped you?

---

p.s I'm at a conference and haven't had time to sit down with Windows, yet, and see if there's anything else I could do.

**Comment by vityou** [comment] 2018-05-14 15:52
I think it should print something like "if your window doesn't show up, try running the program again without deleting this buffer".  Sending something to the frame wouldn't be possible in some cases if the program is still running as the repl wouldn't accept input.

**Comment by alex-hhh** [comment] 2018-05-14 23:58
Any message would be misleading:

* in my case, `(send frame show #t)` fixes the problem, but a frame is not always available. For example, in the `2htdp` there is no toplevel frame exported (as far as I know) so this would not work in that case. I also suspect the problem is that the eventspace for the GUI is not ready yet, and any program that makes use of that eventspace before the window is shown will not be fixed by this workaround.
* re-evaluating twice works, but it seems to me a silly message to print

I can spend some time trying to see what the problem is.  It might also be worth asking about this on racket-users, as the racket developers will know more about how the GUI is initialized.

**Comment by alex-hhh** [comment] 2018-05-15 03:16
Experimenting with this a bit more, I found out that having two show invocations makes it work with racket-mode:

```racket
#lang racket
(require racket/gui)
(define f (new frame% [label "hello"] [width 100] [height 100]))
(send f show #t)
(send f show #t)
```

The original program, with only one "show" invocation, works when racket is started from the command line. That is, saving the code to "example.rkt" and running "racket example.rkt".

@greghendershott , can you confirm that you cannot reproduce this on Linux or OSX? -- this would make it  Windows specific.

**Comment by greghendershott** [comment] 2018-06-04 21:01
I did finally get a chance to try Windows 10 in Virtual Box.

@alex-hhh I see the same behavior as you (on Windows)  regarding the need to show the frame twice.

@vityou when I try [your big bang example](https://github.com/greghendershott/racket-mode/issues/301#issuecomment-388520978) I see the same behavior as you (on Windows).

As I mentioned before, I don't see this same behavior on macOS.

---

I'm not sure what to do about this in racket-mode, other than document this?

**Comment by greghendershott** [comment] 2021-07-17 17:01
I have a commit for this; it shows then immediately hides an initial frame on Windows. Although that's a work-around, it seems to fix this satisfactorily in my testing today.

---

p.s. I'm sorry to be so slow to follow through on this. In recent days I took some time to revisit `racket/gui/base` handling on all platforms, as well as to fix some failing tests on Windows. Windows is now part of CI (easier on GitHub Actions than previously on Travis CI) so that should help going forward.

**Closed** 2021-07-19 12:35 UTC
Labels: bug, windows
