### ISSUE TITLE
Doesn't quite work with parinfer-mode

### ISSUE THREAD

**Issue by andreyorst** [greghendershott/racket-mode#399] opened 2019-08-31 08:09 UTC
Hello. I'm using [parinfer-mode](https://github.com/DogLooksGood/parinfer-mode) to edit lisp code, and like it a lot. However it seems that `parinfer-mode` and `racket-mode` are not compatible. When both `parinfer-mode` and `racket-mode` enabled, parinfer can't automatically balance parens in `indent-mode`:

If I press <kbd>(</kbd> the resulting parens will be:

    (|)

With `|` representing cursor. Next, if I press <kbd>)</kbd>, I expect my cursor to escape parens, but instead additional paren is inserted:

    ()|)

If I do any kind of action, that triggers parinfer's balancing algorithms, for example insert the newline the parens will turn to correct state. Semi-real code example:

![image](https://user-images.githubusercontent.com/19470159/64061141-f2e84f80-cbde-11e9-83d0-88ce37e0c16d.png)

Pressing <kbd>)</kbd>:

![image](https://user-images.githubusercontent.com/19470159/64061147-04c9f280-cbdf-11e9-9ce9-d8b33b114e8f.png)

Exra paren inserted. But if I will add newline:

![image](https://user-images.githubusercontent.com/19470159/64061154-232fee00-cbdf-11e9-8e5c-dec9c04eebcf.png)

Indentation and parens are correct. 

If `electric-pair-mode` is enabled this bug doesn't happen, so I assume that this is related to this issue: https://github.com/greghendershott/racket-mode/issues/140. However `electric-pair-mode` is incompatible with `parinfer-mode` making inserting `"` buggy.

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20190803 1820)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.2")
 (emacs-uptime "1 minute, 24 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820/")
 (racket--rkt-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-revert-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (centaur-tabs-mode)
 (company-flx-mode)
 (company-mode)
 (diff-auto-refine-mode)
 (diff-hl-flydiff-mode)
 (diff-hl-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (electric-indent-mode)
 (eyebrowse-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (gcmh-mode)
 (global-company-mode)
 (global-diff-hl-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-undo-tree-mode)
 (hs-minor-mode)
 (ivy-mode)
 (magit-auto-revert-mode)
 (magit-file-mode)
 (minions-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (parinfer-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (solaire-global-mode)
 (solaire-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-follow-mode)
 (treemacs-fringe-indicator-mode)
 (treemacs-git-mode)
 (undo-tree-mode)
 (window-divider-mode))
(disabled-minor-modes
 (abbrev-mode)
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (centaur-tabs-local-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-hl-dir-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-time-mode)
 (doc-view-minor-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-display-line-numbers-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (line-number-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (orgstruct-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (parinfer-region-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (treemacs-tag-follow-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (vdiff-3way-mode)
 (vdiff-mode)
 (vdiff-scroll-lock-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (with-editor-mode)
 (xref-etags-mode))
```
</details>

**Comment by greghendershott** [comment] 2019-08-31 13:45
From https://github.com/greghendershott/racket-mode/issues/140#issuecomment-107226719:

> In your Emacs init file, please try binding the `)`, `]` and `}` keys in `racket-mode-map` to `self-insert-command`. (You may want to do the same for `racket-repl-mode-map`.)

Can you please try this and let me know if it helps (or not)?

**Comment by greghendershott** [comment] 2019-08-31 15:26
I found a little more time and tried this myself.

I can reproduce the problem you reported (and thank you for the very detailed description!).

I can avoid the problem like so:

```elisp
(use-package parinfer
  :ensure t
  :init
  (setq parinfer-extensions
        '(defaults       ; should be included.
           pretty-parens  ; different paren styles for different modes.
           paredit        ; Introduce some paredit commands.
           smart-tab      ; C-b & C-f jump positions and smart shift with tab & S-tab.
           smart-yank))   ; Yank behavior depend on mode.
  (add-hook 'racket-mode-hook #'parinfer-mode)
  (bind-keys :map racket-mode-map
             (")" . self-insert-command)
             ("]" . self-insert-command)
             ("}" . self-insert-command))
  (bind-keys :map racket-repl-mode-map
             (")" . self-insert-command)
             ("]" . self-insert-command)
             ("}" . self-insert-command)))
```

So I think this is a documentation issue. I'd like to close this issue by adding to [Configure](https://www.racket-mode.com/#Configure) a new sub-section about parinfer-mode (similar to the existing sections for paredit and smartparens), with the above configuration suggestion.

Please let me know what you think.

**Comment by greghendershott** [comment] 2019-08-31 15:30
Note: With this configuration, the extra `]` appears briefly -- then parinfer deletes it. Is that normal behavior for parinfer?

It's seems a little odd, to me. By contrast paredit would behave by not inserting the `]` at all, not even temporarily.

So that seems not 100% perfect, to me. But maybe that's as-expected for parinfer? If so, then I think my proposed change is sufficient.

**Comment by andreyorst** [comment] 2019-08-31 15:36
> With this configuration, the extra ] appears briefly -- then parinfer deletes it. Is that normal behavior for parinfer?

No, this doesn't happen with Emacs Lisp or Scheme modes.

> It's seems a little odd, to me. By contrast paredit would behave by not inserting the ] at all, not even temporarily.

Never used paredit actually, so I do not know if this is something related to it or not. But parinfer should not insert extra `]`.

**Comment by andreyorst** [comment] 2019-08-31 15:51
I've tried your approach and I don't see the `]` inserting problem. That's might be part of your configuration.

Here's relevant parts of my config:

```emacs-lisp
(use-package racket-mode
  :mode ("\\.rkt\\'" . racket-mode)
  :bind (:map racket-mode-map
              ("C-c C-d" . racket-run-with-debugging)
              (")" . self-insert-command)
              ("]" . self-insert-command)
              ("}" . self-insert-command)
              :map racket-repl-mode-map
              (")" . self-insert-command)
              ("]" . self-insert-command)
              ("}" . self-insert-command))
  :config
  (when (fboundp 'doom-color)
    (progn
      (set-face-attribute 'racket-debug-break-face nil :background (doom-color 'red) :foreground "#000000")
      (set-face-attribute 'racket-debug-result-face nil :foreground (doom-color 'grey) :box nil)
      (set-face-attribute 'racket-debug-locals-face nil :foreground (doom-color 'grey) :box nil)
      (set-face-attribute 'racket-selfeval-face nil :foreground (doom-color 'fg)))))

(use-package parinfer
  :commands (parinfer-mode
             parinfer-toggle-mode)
  :hook ((clojure-mode . parinfer-mode)
         (emacs-lisp-mode . parinfer-mode)
         (common-lisp-mode . parinfer-mode)
         (scheme-mode . parinfer-mode)
         (lisp-mode . parinfer-mode)
         (racket-mode . parinfer-mode))
  :bind (:map parinfer-mode-map
              ("C-," . parinfer-toggle-mode))
  :config (setq parinfer-extensions
                '(defaults
                   pretty-parens
                   smart-tab
                   smart-yank)))
```

**Comment by greghendershott** [comment] 2019-08-31 18:12
OK, thanks. If I have time I will try to figure out the "briefly appearing closing delimiter" thing that I'm seeing -- but you aren't. In any case, the core thing here seems to be about Racket Mode binding the closing delimiters to its `racket-insert-closing` command by default.

1. I think documenting this under configuration, as I proposed above, is one reasonable way to close this.

2. I think another reasonable thing might be for Racket Mode to stop doing that: Instead leave the closing delimiter keys bound to `self-insert-command` by default. The "fancier" `racket-insert-closing` predates the existence of -- or at least me knowing about -- `electric-pair-mode`, which is nowadays the "normal" way to do that kind of thing in Emacs. In other words, this might be a case where Racket Mode should stop trying to be "too helpful" in configuring things to "just-work" -- and instead defer to people using the normal Emacs things. (Of course doing this would also entail updating the docs, a little, too, if only to point out `electric-pair-mode` for people who are relatively new to Emacs.)

The more I think about it, I'm leaning toward 2. I guess I'll mull it over a bit, before deciding.

**Closed** 2019-09-02 01:03 UTC
Labels: bug

**Comment by andreyorst** [comment] 2019-09-02 04:16
Thanks!
