### ISSUE TITLE
Racket REPL times out / fails unexpectedly

### ISSUE THREAD

**Issue by blakeshaw** [greghendershott/racket-mode#510] opened 2020-12-08 18:39 UTC
Hi Greg, thank you so much for Racket Mode! I'm thoroughly enjoying learning Racket in Emacs. 

I'm experiencing an issue where, when using Racket Mode _or_ XP Mode, `racket-run-and-switch-to-repl` (kbd f5) will fail unexpectedly, producing the following message:
`match: no matching clause for '(run ("/home/proletkultura/.racket/7.8/sicp_cs/ch1_new.rkt") ((test) (main)) 2048 #t 126 10 medium ...)`

I was experiencing this issue before, and fixed it by installing drracket from raco. The function now _usually_ works and prints to the REPL as expected, but _sometimes_ it will persist even after restarting Emacs. Sometimes I will restart it again and it will be fixed, at other times the issue will persist. I haven't been able to nail down a correlation, unfortunately -- I'll simply be programming and it works, until it fails and produces the above message. This can happen within the first 5 minutes, or within 30, but usually I won't get any further mileage out of Racket-Mode than 30 minutes before the bug occurs.

In case this is useful info, I have had Geiser running with Guile in an org-babel document, but the problem appears to persist even when I'm not running Geiser. 

Let me know if there is anything else I can provide you. Thanks again for Racket-Mode, I imagine I've still made up for the lost time this bug has caused with the productivity I get from using Emacs vs. DrRacket.

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20201123 1623)
		 "Racket editing, REPL, and more"
		 ((emacs
		   (25 1))
		  (faceup
		   (0 0 2))
		  (pos-tip
		   (20191127 1028)))
		 nil nil "/home/proletkultura/.emacs.d/elpa/racket-mode-20201123.1623"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott"))
		  (:commit . "7ccbf43cc17e27d378ce4063c557e1c9b5be7380"))
		 nil))
((emacs-version "26.3")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/proletkultura/.emacs.d/elpa/racket-mode-20201123.1623/")
 (racket--rkt-source-dir "/home/proletkultura/.emacs.d/elpa/racket-mode-20201123.1623/racket/")
 (racket-program "/usr/bin/racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 ...)
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (centaur-tabs-mode)
 (diff-auto-refine-mode)
 (electric-indent-mode)
 ...)
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (centaur-tabs-local-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (compilation-in-progress)
 ...)
</pre>
</details>

**Comment by greghendershott** [comment] 2020-12-09 00:01
Thanks for the report!

> `match: no matching clause for '(run ("/home/proletkultura/.racket/7.8/sicp_cs/ch1_new.rkt") ((test) (main)) 2048 #t 126 10 medium ...)`

It sounds like the Emacs front end is sending a "run" command to the Racket back end, in a format that isn't expected. The Racket `match` error is getting reflected up to the front end and shown to you as an Emacs user error message (which is intentional).

Unfortunately the Racket `match` error message has truncated its display of the non-matching value with "..." -- so I can't quite see the entire value, to get a clue why it's not matching. (The part I see up to the ellipses seems correct.)

---

Idea: Could you please `M-x toggle-debug-on-error`? Then, the next time this happens, Emacs should open a "Backtrace" buffer with an Emacs Lisp call stack. Please copy that entire buffer and paste it into a comment, here.

Hopefully that will have more clues I could follow.

**Comment by greghendershott** [comment] 2020-12-09 00:12
That's odd. When I intentionally pass a bad command, tacking on an extra item to the end of the list, let's say instead of a correct value

    '(run ("/var/tmp/case-lambda.rkt") ((test) (main)) 2048 #t 90 14 medium () ())

I pass

    '(run ("/var/tmp/case-lambda.rkt") ((test) (main)) 2048 #t 90 14 medium () () xxxxx)

then the Emacs error message I see is:

    match: no matching clause for '(run ("/var/tmp/case-lambda.rkt") ((test) (main)) 2048 #t 90 14 medium () () xxxxx)

I see the full bad value. Not truncated with `...)` like in your report.

Also, I notice in the "details" section of your report, the three main lists (showing certain Emacs variables, and enabled and disabled minor modes) are all truncated with `...)`.

I'm not sure why that would be happening. Is your Emacs doing that automatically due to some setting?

It may be N/A for the _cause_ of this bug, but it's making it harder to get info about why it's happening. And I haven't seen that before, with Emacs. So I'm curious.

**Comment by greghendershott** [comment] 2020-12-09 00:20
I dug around and learned about the Emacs `print-length` variable. It looks like you have it set to `10`.

Interestingly, not only is that truncating all your error report and bug report messages.

It seems this might actually also be the _cause_ of this bug. Because Racket Mode uses Emacs print, via a `%S` `format` string, to format the s-expressions to send to the Racket back end.

For me `print-length` is at the default value `nil`. When I change it to `10` I can reproduce your problem.

Do you know you have it set to a non-default value?  Is that on purpose, or did some package `setq` this?

I'm trying to figure out if I need to `let` bind `print-length` back to `nil` around various Racket Mode Emacs Lisp expressions, and how many ....

**Comment by blakeshaw** [comment] 2020-12-09 06:55
Hi Greg -- I added `(setq print-length nil)` to my `.emacs` file, and after applying a `M-x eval-buffer` the problem immediately subsided, so it seems that is the problem! 

before that, I ran `M-x toggle-debug-on-error` but unfortunately the *Backtrace* buffer didn't open when I reproduced the error for whatever reason -- i can confirm that if I put an arbitrary typo `(setqq ...)` in my .emacs file and `M-x eval-buffer`, *Backtrace* opens to tell notify me of the error. 

I knew nothing of `print-length` before this. In my `.emacs` the only snippet containing `print` in any shape is for installing the straight package manager, which I've attached below. For now, I'll remove `(setq print-length nil)` and keep the debug open, and will post here once I get some output on the bug.

<details>
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

**Comment by blakeshaw** [comment] 2020-12-09 08:36
Hi Greg, so I've reproduced the problem after removing `(setq print-length nil)` with `M-x toggle-debug-on-error` on, but unfortunately nothing is reported to the *Backtrace* buffer

**Comment by blakeshaw** [comment] 2020-12-09 11:05
unfortunately it seems I spoke too soon, the `match` error continues to recur periodically, but its seemingly random as i can't pinpoint a cause. if i `M-x eval-buffer` with `(setq print-length nil)` it will start working again, but if i comment it out it won't -- so it seems we're on the right track! I've kept the debugger open but nothing appears in *Backtrace* when the error is triggered. However, I have noticed suspicious looking output in my racket-logger which I've added below
<details>
racket-logger-config:
((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (sequence-specialization . info)
 (* . fatal))
[   info] racket-mode: TCP port 38829 chosen for REPL sessions
[   info] racket-mode: '(1 "*" (check-syntax "/home/proletkultura/.racket/7.8/sicp_cs/ch1_new.rkt" "#lang sicp\n#|\n;; Starting SICP again from the beginning\n\n; Every powerful progr⋯"))
[   info] racket-mode: '(2 "*" (module-names))
[   info] racket-mode: '(3 "*" (repl-tcp-port-number))
[  debug] racket-mode: (call-with-session-context '() #<procedure:command> '((repl-tcp-port-number))): no specific session
[  debug] racket-mode: (call-with-session-context '() #<procedure:command> '((module-names))): no specific session
[  debug] racket-mode: (call-with-session-context '() #<procedure:command> '((check-syntax "/home/proletkultura/.racket/7.8/sicp_cs/ch1_new.rkt" "#lang sicp\n#|\n;; Starting SICP again from the beginning\n\n; Every powerful programming language has three mechanisms\n; for combining simple ideas to form more complex ideas:\n; - Primitive Expressions\n; - Means of Combination\n; - Means of abstraction (nomination)\n\nIn programming we deal with *two kinds of elements*: procedures and data.\n(these actually aren't so distinct)\n\nExpressions like (- 2 2) or (+ 5 6) are called *combinations*\n\nPretty-Printing = writing expressions such that their operands align\np. 11\n|#\n(define pi 3.14159)\n(define radius 10)\n;; To evaluate a combination, do the following:\n; 1) Evaluate the subexpressions of the combination\n; 2) Apply the procedure that is the value of the leftmost subexpression\n; (the operator) to the arguments that are the values of the other subexpressions (the operands).\n(define (square x) (* x x))\n\n(define (sum-of-squares x y)\n  (+ (square x) (square y)))\n\n(define (f a)\n  (sum-of-squares (+ a 1) (* a 2)))\n#|\n1.1.5 The Substitution Model for Procedure Application (p. 18)\nTo apply a compound procedure to arguments, evaluate the body of the procedure with each formal parameter replaced by the corresponding argument.\n\nTwo Major Points of Substitution Model p. 19 - 20\n- The purpose of the substitution is to help us think about procedure application, not to provide a description of how the interpreter really works. Typical interpreters do not evaluate procedure applications by amnipulating the text of a produre to substitute values for formal parameters. In practice, the substitution is accomplished by using a local environment for the formal parameters.\n- The substitution model is the first and simplest of a sequence of increasingly elaborate models of how interpreters work, culminating in the implementation of an interpreter and compiler in ch5. It exists here knowing that it will prove indadequate to describe mutation in Ch.3, when it will be discarded in favor of a stronger model.\n\np. 20 Applicative order VS. Normal Order\nTypically, the interpreter evaluates the operator and the operands, and then applies the resulting procedure to the resulting arguments.\n\nLazy evaluation?:      (no! its just \"normal order evaluation\") -- probably precursor to lazy eval\nAn alternative model wouldn't evaluate the operands until their values are needed.\nInstead, it would first substitute operand expressions for parameters until it obtained an expression involving only primitive operators, and would then perform the evaluation.\nIf we used this method, the evaluation of (f 5) would proceed according to the sequence of expansions:\n(sum-of-squares (+ 5 1) (* 5 2))\n(+ (square (+ 5 1)) (square (* 5 2)) )\n(+ (* (+5 1) (+5 1)) (* (*5 2) (*5 2)))\n\nFollowed by the reductions:\n(+   (* 6 6)   (* 10 10))\n(+ 36 100) = 136\nWe get the same answer, but the process is different. This is \"normal-order evaluation\" as opposed to \"applicative-order evaluation\"\n|#\n; Conditionals p. 22 - 23\n(define (abs-ex x)\n  (cond ((> x 0) x)\n        ((= x 0) 0)\n        ((< x 0) (- x))))\n; The first expression in each pair is a PREDICATE, ie an expression whose value is either true or false.\n; Boolean values and expressions are called predicates in Scheme.\n\n; Another way to write abs is\n\n(define (abs-ex2 x)\n  (cond ((< x 0) (- x))\n        (else x)))\n\n; And yet another\n(define (abs-ex3 x)\n  (if (< x 0)\n      (- x)\n      x)) \n; Exercise 1.1\n; 10 prints 10 / 12 / 8 / 3 / 6 / nothing / nothing / ...too easy keep going\n; Exercise 1.2\n; Translate to prefix form\n(/ (+ (+ 5 4) (- 2 (- 3 (+ 6 (/ 4 5)))))\n   (* 3 (- 6 2) (- 2 7)))\n\n"))): no specific session
[   info] racket-mode: start "repl-session-1607449573635.8323-0"
[   info] racket-mode: '(4 "*" (logger ((cm-accomplice . warning) (GC . info) (module-prefetch . warning) (optimizer . info) (racket/contract . error) (sequence-specialization . info) (* . fatal))))
[  debug] racket-mode: (call-with-session-context '() #<procedure:command> '((logger ((cm-accomplice . warning) (GC . info) (module-prefetch . warning) (optimizer . info) (racket/contract . error) (sequence-specialization . info) (* . fatal))))): no specific session
</details>

**Comment by greghendershott** [comment] 2020-12-09 13:53
Thanks for confirming and the additional details.

- Yesterday I pushed to a topic branch a commit cf5e6a1 that temporarily binds `print-{length level}` while using things like the `%S` format string or `pp`. But I haven't merged it, yet. I'd like to do another pass to look for more places that might need this.

- Your mention of `straight.el` made go look now at their repo, to see if maybe they were `setq`-ing `print-{length level}` to `10`. It seems they're not, but a month ago they added a similar commit: https://github.com/raxod502/straight.el/pull/627.  From a comment it looks like `el-get` might be the culprit, and `straight` is now pulling this in? Or something like that.

So I think TL;DR I should merge my similar commit. Also I should see if `el-get` is indeed doing this bad (IMHO) thing, and if so ask them to stop. I _think_ the spirit of `print-length` and `print-level` is they are supposed to be only `let`-bound, i.e. used much like you'd use `parameterize` with a Racket parameter. But I could be wrong.

**Comment by greghendershott** [comment] 2020-12-09 14:02
Quick glance, `el-get` itself doesn't seem to be the "culprit". Maye it is some package you are using el-get to install.

Anyway I guess it's moot. I should do the defensive thing and let-bind `print-{length level}`. I'll review my commit again this afternoon, then probably go ahead and merge it to the main branch.

**Closed** 2020-12-09 19:07 UTC
Labels: bug

**Comment by greghendershott** [comment] 2020-12-09 19:09
OK I merged this. It will take an hour or two to flow through to MELPA. Or using `straight`, you can get it right away.

Thanks again for reporting this! Although I've learned a lot about Emacs Lisp, apparently there is always more left for me to learn!!

**Comment by blakeshaw** [comment] 2020-12-10 16:16
thank you greg for the amazing support, and for bringing so many of the goodies of drracket to our favorite computing interface! everything is working fine here since the update :)
