### ISSUE TITLE
Args out of range: #<buffer *Racket REPL#> after racket-send-definition

### ISSUE THREAD

**Issue by Herbsi** [greghendershott/racket-mode#407] opened 2019-11-16 07:22 UTC
I'm experiencing the following behavior with `racket-send-definition`:

1. Open a file

For example:
```racket
#lang racket

(define (hello-world)
    (print "hello, world"))
```

2. Run `racket-run`

This opens the REPL and executing `(hello-world)` prints "hello, world".

3. Change the definition of `(hello-world)` to
```racket
(define (hello-world)
    (print "hello, world!"))
```

4. Execute `racket-send-definition with the point at the end of the second line

5. Receive `Args out of range: #<buffer *Racket REPL#>, 15, 64

6. Trying `(hello-world)` in the REPL now does nothing.

<details>

```
((alist-get 'racket-mode package-alist))
((emacs-version "26.3")
 (emacs-uptime "39 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/herwig/.emacs.d/.local/straight/build/racket-mode/")
 (racket--rkt-source-dir "/Users/herwig/.emacs.d/.local/straight/build/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (+popup-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (better-jumper-local-mode)
 (better-jumper-mode)
 (column-number-mode)
 (company-box-mode)
 (company-mode)
 (company-prescient-mode)
 (diff-auto-refine-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (editorconfig-mode)
 (electric-indent-mode)
 (evil-escape-mode)
 (evil-goggles-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-snipe-local-mode)
 (evil-snipe-mode)
 (evil-snipe-override-local-mode)
 (evil-snipe-override-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flycheck-mode)
 (flycheck-popup-tip-mode)
 (font-lock-mode)
 (format-all-mode)
 (general-override-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-so-long-mode)
 (global-undo-tree-mode)
 (goto-address-prog-mode)
 (highlight-numbers-mode)
 (highlight-quoted-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (ivy-mode)
 (ivy-posframe-mode)
 (ivy-rich-mode)
 (line-number-mode)
 (lispy-mode)
 (lispyville-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (persp-mode)
 (prescient-persist-mode)
 (prettify-symbols-mode)
 (projectile-mode)
 (racket-smart-open-bracket-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (solaire-global-mode)
 (solaire-mode)
 (tool-bar-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (vi-tilde-fringe-mode)
 (which-key-mode)
 (whitespace-mode)
 (window-divider-mode)
 (winner-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (+data-vagrant-mode)
 (+emacs-lisp-ert-mode)
 (+eval-repl-mode)
 (+popup-buffer-mode)
 (abbrev-mode)
 (amx-debug-mode)
 (amx-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-time-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (evil-magit-toggle-text-minor-mode)
 (flyspell-mode)
 (general-override-local-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-display-line-numbers-mode)
 (global-hide-mode-line-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-vi-tilde-fringe-mode)
 (global-visual-line-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (goto-address-mode)
 (hide-mode-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lispy-goto-mode)
 (lispy-other-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-file-mode)
 (magit-popup-help-mode)
 (magit-todos-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (pcre-mode)
 (racket-check-syntax-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (rxt--read-pcre-mode)
 (rxt-global-mode)
 (rxt-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-global-strict-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (so-long-minor-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (whitespace-newline-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode))
```
</details>

**Comment by greghendershott** [comment] 2019-11-18 13:55
Thank you for the report.

Unfortunately when I try to reproduce this, I don't get the error message in step 5. Instead, the function is redefined, as expected.

A couple ideas how to proceed -- either/both might help:

1. I wonder what version of Racket Mode you're using?  Normally I could see that from `racket--el-source-dir`. It would be something like `(racket--el-source-dir "/Users/herwig/.emacs.d/elpa/racket-mode-20191112.1417/")` -- the normal package installer includes the version in the directory name.

    But yours is `(racket--el-source-dir "/Users/herwig/.emacs.d/.local/straight/build/racket-mode/")`. IIRC Straight builds source directly from Git repo? Have you refreshed/rebuilt recently? Could you please try that and let me know?

2. Could you please `M-x toggle-debug-on-error`, do steps 1-5 again, and copy that full stack trace buffer here for me to see?

**Comment by Herbsi** [comment] 2019-11-18 15:34
Thanks for your answer.

1 Did not work for me.  Running `git log` inside `"~/.emacs.d/straight/repos/racket-mode/"` gives me `901ce79` for the latest commit, which is from November 12.

Here's the full stack trace from step 5:

```lisp
Debugger entered--Lisp error: (args-out-of-range #<buffer *Racket REPL*> 15 63)
  process-send-region(#<process Racket REPL> 15 63)
  comint-send-region(#<process Racket REPL> 15 63)
  racket--send-region-to-repl(15 63)
  racket-send-definition(nil)
  funcall-interactively(racket-send-definition nil)
  call-interactively(racket-send-definition nil nil)
  command-execute(racket-send-definition)
```

**Comment by greghendershott** [comment] 2019-11-18 17:25
Weird.

The only way I can elicit such an error is to supply an out-of-range value intentionally -- for example by <kbd>M-:</kbd>`(racket--send-region-to-repl 15 99999)`<kbd>RET</kbd>.  Where `99999` is more than `(point-max)`, as in your example.

In your recipe, before you choose `racket-send-definition`, with point at the end of the second line, what if you do <kbd>M-:</kbd>`(list (point) (point-max))`<kbd>RET</kbd>. What value does that return?

p.s. <kbd>M-:</kbd> is a shortcut for <kbd>M-x</kbd>`eval-expression`. I mention that because it looks like you use evil-mode and I don't know its bindings for stuff like this.

**Comment by Herbsi** [comment] 2019-11-18 17:31
`(list (point) (point-max))` yields `(62 64)`

**Comment by greghendershott** [comment] 2019-11-18 19:16
Thanks! In that case I'm really confused. I don't understand why/how it would be an out-of-range error for point to be less than point-max.

I wonder what's going on here....

**Comment by greghendershott** [comment] 2019-11-18 19:20
Oh wait. The top of the call stack says the buffer is ` #<buffer *Racket REPL*>` -- the REPL buffer not the edit buffer. That seems wrong. I'll try to figure out why that is happening (for you but not for me).

**Comment by greghendershott** [comment] 2019-11-19 20:01
I'm still stumped by this.

- I built Emacs 26.3 on Linux to try (normally I just use 25.2.2 from Ubuntu 18.04 LTS package) but still could not reproduce.
- I looked at Emacs C source e.g. process.c and buffer.c for ideas. Nothing jumped out at me.
- I tried enabling some of the minor modes you have active, such as company-mode. No luck.
- Above I commented that I was surprised to see the _buffer_ `#<buffer *Racket REPL*>` in the `args-out-of-range` error. I am. However the call stack below it looks correct; it is normal for the first argument to `send-process-region` to be the REPL *process*. The first argument describes the _target_ of the send. The _source_ region is always in `(current-buffer)`. IIUC.

I'm really not sure how to proceed with this.

- If you're willing, you could try disabling as many minor modes as possible, to see if one of them might be contributing to this somehow (??).
- Maybe another Racket Mode user will chime in to confirm this happens for them, or with some idea about what's going on.

I'm sorry that's all I have, for now. :disappointed:

**Comment by Herbsi** [comment] 2019-11-20 10:46
I've discovered the culprit.  I am using `doom Emacs`, and disabling the `popup` module under `:ui` in my `init.el` fixes the bug.

I'll ask about it at the Doom Discord Server.

Thanks for your help!

**Comment by greghendershott** [comment] 2019-11-20 14:26
Ah! Interesting.

In case it matters, Racket Mode isn't doing anything unusual, here. Things like `inf-lisp` and `cmuscheme` -- and probably anything else in Emacs that interacts with an interpreter running in a so-called "inferior" mode buffer -- use `comint-send-region` (or `process-send-region` directly) to "copy and paste stuff into the REPL".  So, if there is some way in which doom-emacs is changing `current-buffer` at a bad time, it seems likely to affect all of those.

p.s. If you end up [opening an issue on the doom-emacs repo](https://github.com/hlissner/doom-emacs/issues), feel free to link back to this issue.

**Comment by greghendershott** [comment] 2019-11-22 21:18
@Herbsi If you're comfortable trying a temporary "patch":

1. `M-x find-function` and enter `racket--send-region-to-repl`.

2. Edit it slightly, as in this diff:

```diff
modified   racket-repl.el
@@ -581,7 +581,8 @@ the prompt.
 
 Afterwards call `racket--repl-show-and-move-to-end'."
   (when (and start end)
-    (racket-repl t)
+    (save-selected-window ;issue #407
+      (racket-repl t))
     (racket--repl-forget-errors)
     (let ((proc (get-buffer-process racket--repl-buffer-name)))
       (with-racket-repl-buffer
```

3. With point inside that function definition, `M-x eval-defun`.  Now it should be "live".

Try again and see if you still have the problem?

**Comment by Herbsi** [comment] 2019-11-23 07:17
@greghendershott This fixes the issue.

**Comment by greghendershott** [comment] 2019-11-23 15:47
Thanks for trying that and letting me know!

I think that patch confirms the theory of what's happening -- we call display-buffer, which causes doom-emacs/popup also to change the selected window and current buffer, which borks the source for send-region.

That little patch was the simplest thing I could imagine for you to try. Until now, it hadn't occurred to me that something could "sneak in" and change current-buffer here. So I'd like to take a little time to ponder the best solution (maybe this simple patch, maybe not). Regardless, I'll try to push a commit to close this, somehow, within a few days.

**Comment by greghendershott** [comment] 2019-11-26 20:28
@Herbsi If you don't mind trying one more patch, could you please try commit 914c73? If that works for you, I'll merge. Thank you for your help.

(The commit seems better to me because it allows things like doom-emacs/popup to select the REPL buffer. It doesn't prevent or undo that. Instead it simply remembers the original selected buffer, and temporarily restores it only for the comint-send-region.  So if someone likes that "select the REPL" behavior, it will still work.)

**Comment by Herbsi** [comment] 2019-11-27 07:03
@greghendershott Happy to report commit `914c73` fixes the issue for me.  Thanks a lot.

**Closed** 2019-11-27 15:28 UTC
Labels: bug, cannot-reproduce

**Comment by greghendershott** [comment] 2019-11-27 15:29
Thank you for letting me know!

Merged to `master` and pushed.
