### ISSUE TITLE
potential memory leak when editing large `#lang brag` file

### ISSUE THREAD

**Issue by tgbugs** [greghendershott/racket-mode#512] opened 2020-12-17 02:52 UTC
I'm leaving this as a note that I am seeing what appears to be a memory leak when working with a large `#lang brag` file. I have not been able to pin down the issue, but the behavior is essentially that the background racket process's memory usage slowly increases over time and I usually notice after returning from being away from the computer because my memory usage is about to cause the OOM killer to start hunting. It tops out at around 6gigs resident (a bit odd given that the limit is 2048?). I don't have the large brag file somewhere visible at the moment but will link it here once it is.

If I had to hazard a guess about what was going on, it would be that `racket-xp-mode` is repeatedly expanding the file and that the expansions are large and are somehow not being cleaned up, but I have zero evidence to support that.

Racket version is 7.9 bc.
Emacs version is multiple different builds from the `feature/native-comp` branch.

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "28.0.50")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode lisp-interaction-mode)
 (racket--el-source-dir "/home/tom/.emacs.d/racket-mode/")
 (racket--rkt-source-dir "/home/tom/.emacs.d/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-images-system-viewer "display")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-echo-area)))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (column-number-mode)
 (completion-in-region-mode)
 (csv-field-index-mode)
 (display-line-numbers-mode)
 (eldoc-mode)
 (electric-pair-mode)
 (eval-sexp-fu-flash-mode)
 (evil-local-mode)
 (evil-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-undo-tree-mode)
 (global-visual-line-mode)
 (highlight-numbers-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (mouse-wheel-mode)
 (outline-minor-mode)
 (override-global-mode)
 (rainbow-delimiters-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (visual-line-mode)
 (which-function-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-complete-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (bibtex-completion-notes-global-mode)
 (bibtex-completion-notes-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (button-mode)
 (cider--debug-mode)
 (cider-auto-test-mode)
 (cider-enlighten-mode)
 (cider-mode)
 (cider-popup-buffer-mode)
 (cl-old-struct-compat-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (csv-align-mode)
 (cua-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (electric-indent-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (elpy-django)
 (elpy-mode)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (eshell-var-mode)
 (evil-leader-mode)
 (evil-magit-toggle-text-minor-mode)
 (evil-org-mode)
 (evil-paredit-mode)
 (fci-mode)
 (flycheck-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-auto-complete-mode)
 (global-auto-revert-mode)
 (global-evil-leader-mode)
 (global-flycheck-mode)
 (global-goto-address-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-linum-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (gnuplot-context-sensitive-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-display-line-numbers-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (julia-repl-mode)
 (linum-mode)
 (macrostep-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (ob-ipython-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-make-toc-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgstrap-edit-mode)
 (orgtbl-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (pycoverage-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-org-mode)
 (recentf-mode)
 (rectangle-mark-mode)
 (reftex-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (show-paren-mode)
 (size-indication-mode)
 (slime-autodoc-mode)
 (slime-edit-value-mode)
 (slime-editing-mode)
 (slime-fuzzy-target-buffer-completions-mode)
 (slime-macroexpansion-minor-mode)
 (slime-mode)
 (slime-popup-buffer-mode)
 (slime-repl-map-mode)
 (slime-repl-read-mode)
 (slime-trace-dialog-autofollow-mode)
 (slime-trace-dialog-hide-details-mode)
 (slime-trace-dialog-minor-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (vdiff-3way-mode)
 (vdiff-mode)
 (vdiff-scroll-lock-mode)
 (view-mode)
 (visible-mode)
 (vterm-copy-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by capfredf** [comment] 2020-12-17 16:24
just wanted to chime in. Yesterday at one backend, the backend server was using 18GB of memory....

**Comment by greghendershott** [comment] 2020-12-18 17:55
Thanks for the heads up. I would definitely like to investigate.

>  It tops out at around 6gigs resident (a bit odd given that the limit is 2048?)

I should improve the documentation for `racket-memory-limit` to make clear that it applies to your user program. In other words, this uses `custodian-limit-memory` on a custodian that is made for each `racket-run` of your program.

>  I don't have the large brag file somewhere visible at the moment but will link it here once it is.

That would be great!  I'd like to be able to see what you're seeing.

> If I had to hazard a guess about what was going on, it would be that racket-xp-mode is repeatedly expanding the file and that the expansions are large and are somehow not being cleaned up, but I have zero evidence to support that.

It does keep a cache of expansions -- because expansion can be so slow, and various things work on fully-expanded syntax: Check-syntax, finding definition sites, and of course evaluating the program when there isn't any compiled `.zo`. All of these benefit from reusing the cached expansion. There are even scenarios like: You type a few characters, but before check-syntax kicks in, you undo. When check-syntax does kick in, the digest matches what's in the cache and it (quickly) uses that again.

The cache is a hash-table. The hash-table key is the source file pathname. The hash-table value includes the original syntax, the expanded syntax, and also an MD5 digest of the file contents. So, a given source file will remain in the cache "forever", but only _one_ version of it.

As a result, if you're working with the same set of source files for 10 minutes vs. 10 hours, I wouldn't expect the cache working set to be any bigger (modulo your source edits over time actually making the expanded result any bigger).

That's what I _expect_. And I've never seen an OOM situation. But maybe I'm not using "heavy" enough examples. So again I'd love to try your file if/when you're able to share that.

p.s. I could add time expiry. Initially I'd planned to. But later I managed to feel unsure it would actually provide a significant benefit. I wasn't sure what reasonable expiration times would be. Too long, and expiration is N/A. Too short, and the cache becomes N/A (becomes a complication that is effectively a non-cache). Having said that, assuming the memory growth is due to the cache, and not something else, I'd definitely be willing to look at this again!

**Comment by tgbugs** [comment] 2020-12-18 20:21
> this uses `custodian-limit-memory` on a custodian that is made for each `racket-run` of your program.

Given there was only a single background process I wondered whether this might be how you had implemented it, good to know.

> a given source file will remain in the cache "forever", but only one version of it
> assuming the memory growth is due to the cache, and not something else

Given your description it seems like the cache shouldn't be growing in the way I'm seeing, and I will keep this in mind as I hunt down what is going on. Will report back when I have a clearer idea/the file that can trigger the issue.

**Comment by greghendershott** [comment] 2020-12-18 21:32
I added some logging to the syntax cache. And doing a lot of editing in a file, prompting many check-syntaxes. So far, I'm not seeing the cache itself grow. Nor `current-memory-use`; well, it grows for awhile, then apparently a Racket major GC kicks in and shrinks it, then it resumes growing... as you'd probably expect.

I also tentatively added a field to track the LRU for each entry, and a thread to check at interval and purge things above a certain age. It's not horribly complicated, but, I'm not sure I want to commit and merge that. Let's learn more, if we can, about what exactly you're experiencing...?

---

By the way, not that you should _need_ such a work-around, but you can always `M-x racket-start-back-end`. This will kill the back end if it's running, then start it. It is pretty quick.

So, in parallel to maybe helping me debug this, if you ever see a huge memory use, that's how to <kbd>CTRL+ALT+DEL</kbd> -- which is always the best tech support advice. :smile:

But in all seriousness I would love to get to the bottom of this.

**Comment by tgbugs** [comment] 2020-12-18 22:05
> you can always `M-x racket-start-back-end`. This will kill the back end if it's running, then start it. It is pretty quick.

Welp. That's what I get for not reading the manual and searching in vain for something like `racket-restart-back-end`. `defalias` here we come! It will definitely come in handy.

**Comment by greghendershott** [comment] 2021-01-25 15:46
>> I don't have the large brag file somewhere visible at the moment but will link it here once it is.
>
> That would be great! I'd like to be able to see what you're seeing.

@tgbugs I just wanted to check in and see if it turned out you were ready/willing to share that example file or repo.

If so, it would be a great way to jump-start looking at this, again. (I'd explored some ideas before, but wasn't able to really zero in on what is happening.)

If not, that's OK, I can try to think of some other angle from which to tackle it.

**Comment by tgbugs** [comment] 2021-01-25 16:14
@greghendershott will definitely share it, I've just been slammed all Jan, I'll try to get it up this week or next weekend.

**Comment by greghendershott** [comment] 2021-01-28 19:01
@tgbugs No worries. Thanks again for reporting the issue, and for offering to share the file when you can.

The last couple days, I have tried to dig into this more, anyway. Still working on the assumption (?) this is due to the expanded syntax caching. I have some changes that allow a major GC to evict items from the cache. But I'm still dog-fooding and thinking. I might merge it, even before getting your example file. My hesitation, so far, is due to:

1. I don't want that change to cause a new problem.

2. The recovery is fairly "chunky": Nothing is freed until a major GC, and then nearly everything is freed.

3. Even prior to this change, I was having trouble finding a recipe for the memory use to grow unbounded -- I would see it "zig zag" up then down, but not really trending up. I'm not sure my change really affects that materially.  Plus I'm not sure it addresses the root cause of the very large numbers you and @capfredf reported seeing. I still haven't seen those, yet. Might be related to the programs being run. Anyway I'll keep thinking....

**Comment by greghendershott** [comment] 2021-01-29 01:00
OK I found a scenario where I can get memory use to grow indefinitely: Opening a few dozen files that use Typed Racket, with `racket-xp-mode` enabled.

I think this may be due to the implementation of #451. Disabling that seems to avoid the problem.

- I'll figure out how to re-implement it without leaking.

- Also I'll keep looking for more potential leak sources.

**Comment by capfredf** [comment] 2021-01-29 02:35
BTW, editing some large racket files ([ex1](https://github.com/racket/typed-racket/blob/master/typed-racket-test/unit-tests/typecheck-tests.rkt)) gets the backend server to stuck at 100% CPU. I usually need to kill the buffers and restart the backend server (by calling `racket-start-back-end`) after editing those files.

**Comment by greghendershott** [comment] 2021-01-29 03:09
I left a thumbs-up on that, not to mean "I confirmed that", but thank you for a "torture test case". Even though that one didn't pan out, I appreciate it. So I'll leave the thumbs-up. :)

**Comment by greghendershott** [comment] 2021-02-02 21:55
I've continued working on this, doing more experiments and tests. I'm going to merge 3e63bdc for release. I think it will at least mitigate what both of you are seeing. It might even solve it.

**Comment by greghendershott** [comment] 2021-02-03 15:37
Commit 3e63bdc is [live on MELPA >= 20210202.2145](https://melpa.org/#/racket-mode) if that's an easier way to try it.

If neither of you has a chance to try this, soon, then of course no worries -- I understand and I'm glad to stand down for awhile.

**Comment by tgbugs** [comment] 2021-02-03 15:55
I've been doing a test on the 20210125 (d1cbeb7e1e565071a5fd122a4c34ecf534bb0e09) release on melpa with the file that was causing the issue before and I haven't had any issues so far. I will test the new release as soon as I can figure out why use-package insists on ignoring my load-path to the git version in favor of the melpa version.

**Comment by tgbugs** [comment] 2021-02-05 21:10
Ok, I've had the originally offending file up and open for a couple of days running against 3e63bdc5bdc5a9d0a28f3568fa994a5792c447c5 and have not encountered the leak, so it seems that it might be fixed. I will report back if I run into the issue again. Thanks!

**Comment by greghendershott** [comment] 2021-02-06 16:05
I added a "stress test" to open 500 .rkt files:

```racket
(module+ slow-test
  (require rackunit
           racket/file
           racket/path)
  (for ([_ 2]) (collect-garbage))
  (define least (current-memory-use))
  (define most  least)
  (define count 0)
  (for* ([roots (in-list '(("racket.rkt" "typed")
                           ("core.rkt" "typed-racket")
                           ("main.rkt" "racket")))]
         [path  (in-directory
                 (path-only
                  (apply collection-file-path roots)))]
         #:when (equal? #"rkt" (filename-extension path)))
    (set! count (add1 count))
    (check-syntax (path->string path) (file->string path))
    (define after (current-memory-use))
    (printf "~a, ~a, ~v\n" count after (path->string path))
    (set! least (min least after))
    (set! most  (max most  after)))
  (printf "Least: ~a\n" least)
  (printf "Most:  ~a\n" most))
```

The memory use looks like:

![current-memory-use](https://user-images.githubusercontent.com/265119/107123202-3c27de80-686a-11eb-91c7-77007c3edaba.png)

So, I think the original issue is now fixed. Before closing I'd love to hear back also from @capfredf who saw even more extreme memory use.

---

p.s. I think the expanded syntax for Typed Racket programs is significantly larger. I'm not sure exactly why (if the syntax objects are more complicated, and/or their scope sets, and/or syntax properties hold references to more/bigger things, and/or other things). Although I'm curious about that I think it's N/A for this issue, it's not as if TR is doing anything wrong.

**Comment by capfredf** [comment] 2021-02-06 16:56
Thank you for very much @greghendershott! I will report back if I see similar issues arise again

**Comment by greghendershott** [comment] 2021-02-18 14:22
Based on your feedback, and my own usage: I believe this is resolved. I'm going to close it.

**Closed** 2021-02-18 14:22 UTC
Labels: bug

**Comment by tgbugs** [comment] 2021-04-30 02:24
One final report to say that I have been editing the offending file again for long periods of time and no issues have been encountered, so further evidence that this has been fixed.
