### ISSUE TITLE
Racket REPL hanging editor with contract violation complain every now and then

### ISSUE THREAD

**Issue by BitPuffin** [greghendershott/racket-mode#126] opened 2015-04-19 20:57 UTC
So every now and then, the editor hangs for a few seconds because the racket REPL wants to complain about some contract violation stuff.

This happened to me now for example with this code

``` racket
#lang racket

(provide command-structure)

(require mys/command)

(define aliases '("list-branches" ""))
```
I was adding stuff to the aliases list and every time I started a new string the racket REPL interrupted me saying:

``` racket
; symbol->string: contract violation
;   expected: symbol?
;   given: "list-branches"
; Context:
;  /Users/isak/.emacs.d/elpa/racket-mode-20150405.716/cmds.rkt:239:0 sig
;  /Users/isak/.emacs.d/elpa/racket-mode-20150405.716/cmds.rkt:231:0 type
;  /Users/isak/.emacs.d/elpa/racket-mode-20150405.716/cmds.rkt:49:0
```

**Comment by greghendershott** [comment] 2015-04-19 22:13
That's odd. How that `sig` function would be called is when you choose `racket-describe` (bound to <kbd>C-c C-.</kbd> by default). But even if you were issuing that command accidentally, somehow, that contract failure shouldn't happen. So I'm doubly puzzled.

I can't reproduce it, so, could please you try updating to the latest `racket-mode` from MELPA, and let me know if it still happens (or not)?

**Comment by greghendershott** [comment] 2015-04-21 18:17
@BitPuffin I'm still stumped how this would happen. If you do have a chance to try again with the latest version, please let me know?

Also:

> every time I started a new string the racket REPL interrupted me saying...

Do I understand correctly that this happened every time you typed the opening `"`? If so, what does <kbd>C-h k "</kbd> report?

Or if was in reaction to some other, specific key, please let me know about that?

Thank you.

**Comment by samertm** [comment] 2015-04-25 07:58
Hi from a fellow RCer!

I can reproduce this consistently with the latest racket-mode on melpa (20150423.1420), a build of the latest verison of racket (6.1.1), and a snapshot of the latest version of emacs (GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.12) of 2015-04-24) with the following snippet:

```racket
#lang racket

("/" 
```
(There's a space after `"/"`)

And this is the error I get in *Racket REPL*:
```
test.rkt﻿> ; symbol->string: contract violation
;   expected: symbol?
;   given: "/"
; Context:
;  /home/samer/.emacs.d/elpa/racket-mode-20150423.1420/cmds.rkt:243:0 sig
;  /home/samer/.emacs.d/elpa/racket-mode-20150423.1420/cmds.rkt:235:0 type
;  /home/samer/.emacs.d/elpa/racket-mode-20150423.1420/cmds.rkt:50:0
```

racket-mode is great, btw :) I'm organizing EmacsConf 2015, and it would be awesome if you came and gave a talk! Interest form: https://goo.gl/forms/tv0sDuApd8

**Comment by samertm** [comment] 2015-04-25 08:14
Also, if something is running in \*Racket REPL\*, racket-mode will just constantly stall. So if you call racket-run in a buffer with this:
```racket
#lang racket
(require web-server/servlet web-server/servlet-env)
(define (start req) (response/xexpr "test"))

(serve/servlet start)
```

And without closing the server, start writing `(define ` (or anything else). racket-mode will stall. Not sure if these two bugs are related, though. What function is being called when you type `(some-chars ` (with the space)?

**Comment by greghendershott** [comment] 2015-04-25 14:16
> I can reproduce this consistently with the latest racket-mode on melpa (20150423.1420), a build of the latest verison of racket (6.1.1), and a snapshot of the latest version of emacs (GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.12) of 2015-04-24) with the following snippet:

Thanks for the version details.

> What function is being called when you type "(some-chars " (with the space)?

That's an excellent question. I should have focused on that, all along. The answer is, it depends on what else you're using. I normally do _not_ `eldoc-mode` or `company-mode` enabled, for example.

When I <kbd>M-x turn-on-eldoc-mode</kbd>, bingo, I can reproduce this right away.  Thanks!

**Comment by greghendershott** [comment] 2015-04-25 14:28
p.s. @samertm 

> Hi from a fellow RCer!

Hi! I plan to visit for reunion week, how about you?

> I'm organizing EmacsConf 2015, and it would be awesome if you came and gave a talk! Interest form: https://goo.gl/forms/tv0sDuApd8

I know, and I signed up. Just to attend, though. I gave a talk about racket-mode at RacketCon this past October. But I feel intimidated about an Emacs conference. I feel like any talk I could give would be, "I'm still figuring out things about Emacs that the audience knew 5 (or 20) years ago".

**Closed** 2015-04-25 19:39 UTC
Labels: bug

**Comment by samertm** [comment] 2015-05-07 11:41
Hmm, I'm still seeing this issue with a running server (the second example) w/ the latest version of racket-mode.

> Hi! I plan to visit for reunion week, how about you?

I'm not flying out (too expensive :) ), when are you going to be in SF though? And I might pick up RacketCon tickets :)

> But I feel intimidated about an Emacs conference. I feel like any talk I could give would be, "I'm still figuring out things about Emacs that the audience knew 5 (or 20) years ago".

That just means you relate to the entire Emacs audience :) I would be really fascinated to hear you talk about what you've learned about elisp by writing this mode, and how elisp contrasts with Racket. I'll follow up with an email.

**Comment by BitPuffin** [comment] 2015-05-07 11:44
I forgot about this @greghendershott. I'm not entirely sure how to reproduce it, it seems to happen on a few different occasions. Also I was using the latest github version when it happened I believe. I'll let you know when I write some more racket code because it pretty much happens every time I ever use racket-mode

**Comment by greghendershott** [comment] 2015-05-07 14:31
@samertm 

> Hmm, I'm still seeing this issue with a running server (the second example) w/ the latest version of racket-mode. 

OK, that's different. That's as-expected, to _me_, but understandably not to you. I'll open a fresh issue for that.

Basically, the communication mechanism is that the edit buffer "types things for you" into the REPL buffer. At the REPL prompt, if you type `,help` you will many of these "commands". For example you could type `,sig foo` and see the function signature (if available) for `foo`. When the eldoc code needs a sig, basically that is what's happening behind the scenes.

As a result, unless the REPL is "ready" at a prompt, the commands can't be sent. (You can <kbd>C-c C-c</kbd> in the REPL to break the running Racket program. I mean that the edit buffer can't send the "hidden commands".)

Generally this works well and is very reliable (there are no thread synchronization issues for example). Except in the use case you described: Keeping something like a server running a long time in the REPL while continuing to edit.

Probably I should redesign this to use a socket and work out how to synchronize things and efficiently handle programs that emit a huge amount to stdout, etc. etc.  For the last few months I've been working mostly on a `debugger` branch. If possible I'd like to finish that, first.

**Comment by samertm** [comment] 2015-05-07 16:18
Ah, I assumed something like that was going on. Thanks for replying so
quickly!
