### ISSUE TITLE
multiline comment is not recognized

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#362] opened 2019-02-13 15:25 UTC
Specifically, when the comment starts with a paren. E.g.,

```
#|(hello)|#
```

Note that

```
#| (hello)|#
```

works fine.

**Comment by greghendershott** [comment] 2019-02-13 19:41
In case anyone has time to look at this before I can:

- It is probably related to [this](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L84-L85) and/or [this](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L132-L140).

- It would be good to add both examples [here](https://github.com/greghendershott/racket-mode/blob/master/racket/example/example.rkt#L102) as regression tests, following the instructions at the head of the file how to regenerate for faceup.

**Comment by sorawee** [comment] 2019-02-13 20:00
Another buggy case:

```
#|aaa() |#
```

Note that

```
#|aaa|#
```

works fine.

**Comment by greghendershott** [comment] 2019-02-14 03:20
By the way, racket-mode has good (AFAIK) support for s-expression comments. Sticking `#;` in front of an s-expression can be faster to do (and later undo) than using multi-line comments.

I mention that as a tip. Also it's probably why I hadn't encountered this bug. Regardless, I agree it would be nice for the bug to be fixed by someone including but not limited to me.

**Comment by sorawee** [comment] 2019-02-14 05:30
I agree that the S-expression comment is better. However, the instance that I saw this is someone else's code, which was highlighted incorrectly due to the bug.

**Comment by alex-hhh** [comment] 2019-04-04 08:09
The problem is indeed in the syntax propertize function, but it is because the "reader literals" case also catches the "#|" combination.   This fixes the comment highlighting issue:

```diff
--- a/racket-common.el
+++ b/racket-common.el
@@ -115,6 +115,12 @@
     ;; comment. Instead special-case `racket-send-last-sexp'.
     ((rx "#;")
      (0 "'"))
+    ((rx "#|")
+     ;; Skip #| (comment start) from being caught by the reader
+     ;; literals rule below.  We don't want to propertize anything in
+     ;; this string, but the only way I found how to do it is to
+     ;; attempt to propertize a non-existent group.
+     (10 "w"))
     ;; Treat "complex" reader literals as a single sexp for nav and
     ;; indent, by marking the stuff after the # as prefix syntax.
     ;; Racket predefines reader literals like #"" #rx"" #px"" #hash()
```

**Comment by greghendershott** [comment] 2019-04-04 15:01
@alex-hhh Thank you for narrowing this down!

To a topic branch I just pushed commit 3bd4e06.

Although that uses a _slightly_ different fix and adds regression tests, you drove the ball on the green; I just did a couple short putts.

**Closed** 2019-04-04 19:33 UTC
Labels: bug, help-wanted

**Comment by alex-hhh** [comment] 2019-04-04 22:36
Yes, I suspected the regexp for the reader literals could be fixed, but I didn't want to learn the `rx` syntax for the purpose of fixing this bug, this is why I didn't submit a pull request :-)
