### ISSUE TITLE
Indentation of for/flvector

### ISSUE THREAD

**Issue by PLu55** [greghendershott/racket-mode#352] opened 2019-01-24 14:41 UTC
The indentation for `for/flvector` doen't look like expected. It now look like:

```racket 
(for/flvector #:length n ((e state))
              (if (number? e)
                  e
                  0.0))
                          
```
It's expected to look like:

```racket 
(for/flvector #:length n ((e state))
  (if (number? e)
      e
      0.0))
                          
```
Racket-mode version: 20181206.329

**Comment by greghendershott** [comment] 2019-01-24 21:40
Between the optional keyword arguments, and optional types in the Typed Racket flavors, some of the `for` forms can be tricky indent without custom Elisp.

As a quick hack, until I or someone else can take a look at this:

You could set the indent for `for/flvector` to `'defun`, in your Emacs init file or even as a file variable setting in the .rkt file.  That will at least handle the case where you squeeze things on the first line, as in your expected example. (It just won't handle having `#:length n` and `([e state])` on separate lines.)

**Comment by greghendershott** [comment] 2019-01-24 21:43
cf #68

**Comment by greghendershott** [comment] 2019-01-24 21:52
Actually I cannot reproduce this. It indents as you expect, for me.

In fact this seems like a duplicate of #68 from 2014 -- although that was about `for/vector` instead of `for/fl-vector`, the cause and the fix are the same.

---

If you go to that .rkt file you're editing, do <kbd>A-:</kbd>, and enter `(get 'for/flvector 'racket-indent-function)`, what is the result? Is it `racket--indent-for`, or something else?

**Comment by PLu55** [comment] 2019-01-25 06:16
I updated from version 20181206.329 to 20190116.1853 and now the indentation is as expected.

**Comment by greghendershott** [comment] 2019-01-26 01:08
No worries; glad to hear it's working.

**Closed by greghendershott** 2019-01-26 01:08 UTC
Labels: bug, cannot-reproduce
