### ISSUE TITLE
A lot of lag on every input, when flycheck-mode is on

### ISSUE THREAD

**Issue by krux02** [greghendershott/racket-mode#554] opened 2021-08-27 09:19 UTC
I just installed racked mode. No prior experience with racket yet, I am just doing the tutorial. I already experience major performance problems in very small files. There is input lag on every character that I type. Entering newline is the worst character so far, it can take several seconds before the change is visible in emacs. 

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20210727 1545)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1))
                  (faceup
                   (0 0 2))
                  (pos-tip
                   (20191127 1028)))
                 nil nil "/home/arne/.emacs.d/elpa/racket-mode-20210727.1545"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott"))
                  (:commit . "ef9a3fed943495ec2b0c8258f8e00307d6434b17"))
                 nil))
((emacs-version "27.2")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/arne/.emacs.d/elpa/racket-mode-20210727.1545/")
 (racket--rkt-source-dir "/home/arne/.emacs.d/elpa/racket-mode-20210727.1545/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function identity)
 (racket-path-from-racket-to-emacs-function identity)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-image-file-mode)
 (auto-save-mode)
 (column-number-mode)
 (cua-mode)
 (delete-selection-mode)
 (display-time-mode)
 (file-name-shadow-mode)
 (flycheck-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (ivy-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (mouse-wheel-mode)
 (projectile-mode)
 (recentf-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tabbar-mode)
 (tabbar-mwheel-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (visual-line-mode)
 (which-function-mode)
 (whole-line-or-region-global-mode)
 (whole-line-or-region-local-mode)
 (winner-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (cl-old-struct-compat-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-indent-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (exwm-debug)
 (flx-ido-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-dash-fontify-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (remember-notes-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (tabbar-local-mode)
 (tar-subfile-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (vterm-copy-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xcb:debug)
 (xref-etags-mode))
</pre>
</details>

**Comment by krux02** [comment] 2021-08-28 15:06
I am currently not at home, but I can answer you a few questions already right now:

 * Slow typing is in racket-mode, I did not yet test racket-repl-mode
 * eldoc-mode is enabled. ``global-eldoc-mode`` is listed in the details.

**Comment by krux02** [comment] 2021-08-28 23:37
I am not ready to answer all questions properly:

 * I am using `racket-mode`, `racket-repl` doesn't work for some raeson at all. Just tested it, in `racket/debug.rkt:4:9`: collection not found.
 * I've global eldoc-mode enabled. result of ``M-x eldoc-mode`` prints "There is no ElDoc support in this buffer"
 * Yep, I've disabled flycheck mode and I can edit files again. I put it in the title now.

**Comment by greghendershott** [comment] 2021-08-29 13:40
Thank you for narrowing it down to `flycheck-mode`.

I tried myself just now. I also find `flycheck-mode` to be laggy. Not nearly as bad as you reported (I don't see multi seconds delay after a newline). But it is slower enough to be noticeable, and annoying.

---

I don't usually use `flycheck-mode`. I don't know what's considered a "normal" experience. Also I don't know its configuration options.

So I think in parallel:

1. I'll dig around to see if `flycheck-mode` is particularly slow with `racket-mode`, and if so, is there something I can do to improve it.

2. Meanwhile, I'd suggest you not use `flycheck-mode` and instead use Racket Mode's [`racket-xp-mode`](https://www.racket-mode.com/#racket_002dxp_002dmode). I think that will give you >= the benefit as flycheck and I think you'll find it a better experience. (Of course if you disagree, or if you have problems with _that_, please let me know!)

**Comment by krux02** [comment] 2021-08-29 14:15
Generally speaking, flycheck and eldoc are great modes for emacs lisp. I don't notice lag in this language at all. Other languages haved mixed quality in flycheck integration. Often in the direction of too many badly implemented features that the entire major mode is useless unless you disable all these modes. Regarding the performance. I tested it on an old Thinkpad X201 Tablet. It is not a modern machine by any means and therefore performance problems get amplified. I also test my projects on it for my low end hardware support.

Regarding `racket-xp-mode` it looks to me like a combination of eldoc, flycheck and company mode. For some reason in emacs every feature is separated into different modes and you can enable and disable them as you like.

My ideas (without any further research) would be the following:

 * Disable flycheck mode like eldoc mode. Eldoc properly reports that it isn't supported and therefore no problems.
 * Provide flycheckmode integration, but forward everything to racket-xp-mode (same for eldoc and company).
And yes I will disable flycheck mode and use racket-xp-mode instead.

**Comment by greghendershott** [comment] 2021-08-29 14:48
`flycheck-mode` for Racket, from what I can see in the source, essentially does a `raco expand`. This is useful to catch errors.

`racket-xp-mode` uses a `check-syntax` facility provided by Racket to do a deeper analysis that is useful even when the program has no errors or warnings. It is an optional minor mode; you can use it or not in the usual Emacs way. It can be a _source_ of completion candidates and documentation information for things like `company-mode` and `eldoc`, but it isn't a replacement for them.

I am not sure why `flycheck-mode` is laggy for both of us. Presumably it is the same cause, and the effect is greater on your older X201 (?).  Although it seems unlikely that it's the "fault" of `racket-mode`, I'm not closing this as "not my problem!"; as I said I'll investigate to make sure. I'll even make a PR to `flycheck-mode` if I find something to fix or improve on their end.

**Comment by greghendershott** [comment] 2021-08-29 16:53
OK I spent some time trying to understand the flycheck source.

- You might want to change its customization variable `flycheck-check-syntax-automatically` to remove `new-line` from the list. That should fix the big delay after you add a newline, because it will no longer force an immediate check. (If an immediate check is harmless or even desirable for some langs, note you could `setq-local` this to have a different value in some buffers like `racket-mode` than in others.)
- Even after that change, with `idle-change` still in the list, it will still trigger a check after `flycheck-idle-change-delay` seconds, which for me is 0.5 seconds. You might want to increase that delay?
- If after all that, you're still experiencing a significant delay after typing non-new-line characters, one by one (which I'm not really seeing): I don't have an answer. That might be worth asking about at flycheck's github issues?

---

I _think_ this means there's nothing special that Racket Mode ought to do do wrt flycheck-mode. It seems like this is mainly about how to configure flycheck to work better on a slower/older computer. Having said that, I'll keep this issue open for now in case you disagree or have new information.

**Comment by krux02** [comment] 2021-08-31 23:42
> I'll keep this issue open for now in case you disagree or have new information.

Yes I do disagree, this Answer even annoys me, but I try to explain calmly why this is the case. 
We could reduced the problem so far to "racket to flycheck integration causes input lag" and now you suggest as a solution, that I should turn down flycheck. That doesn't address the problem "racket to flycheck integration causes input lag" at all.

I use flycheck for quite some time now, it is not perfect, but for many languages it works without problems, so I would rather try to figure out why it works so well for other languages, but in racket-mode it causes input lag? If the problem is in flycheck wouldn't that mean that all languages would have the same problem?

But your answer even made me investigate what exactly caused the slowdown and I did some profiling to find out where most of the time is spend. And yes, a lot of time is spend in flycheck, namely ``flycheck-tokenize-output-witch-patterns``. Setting a breakpoint told me how the function was called, this is what the debugger told it about its arguments:

```
 * flycheck-tokenize-output-with-patterns("(module flycheck_scratch racket\n  (#%module-begin\n   (module configure-runtime '#%kernel\n     (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))\n   (#%require (for-meta 1 syntax/parse))\n   (define-syntaxes\n    (print)\n    (lambda (form)\n      (let-values (((x) (#%app datum->syntax '#f form)))\n        (let-values (((this-syntax1) x))\n          (let-values ()\n            (let-values ()\n              (let-values ()\n                (let-values (((ctx0)\n                              (#%app normalize-context 'syntax-parse x x)))\n                  (let-values (((pr) (#%app ps-empty x (#%app cadr ctx0))))\n                    (let-values (((es) '#t))\n                      (let-values (((cx) x))\n                        (let-values (((fh0) (#%app syntax-patterns-fail ctx0)))\n                          (with-continuation-mark\n                           parameterization-key\n                           (#%app\n                            extend-parameterization\n                            (#%app\n                             continuation-mark-set-first\n                             '#f\n                             parameterization-key)\n                            current-syntax-context\n                            (#%app cadr ctx0)\n                            current-state\n                            '#hasheq()\n                            current-state-writable?\n                            '#f)\n                           (let-values ()\n                             (let-values (((fail-handler3) fh0)\n                                          ((cut-prompt4) fh0)\n                                          ((undo-stack5) null))\n                               (let-values ()\n                                 (let-values ()\n                                   (let-values ()\n                                     (let-values (((fail-handler9)\n                                                   (lambda (undos2 fs2)\n                                                     (#%app\n                                                      unwind-to\n                                                      undos2\n                                                      undo-stack5)\n                                                     (#%app\n                                                      fail-handler3\n                                                      undo-stack5\n                                                      fs2)))\n                                                  ((undo-stack10) undo-stack5))\n                                       (let-values ()\n                                         (let-values ()\n                                           (let-values (((datum)\n                                                         (if (#%app syntax? x)\n                                                           (#%app syntax-e x)\n                                                           x))\n                                                        ((cx)\n                                                         (if (#%app syntax? x)\n                                                           x\n                                                           cx)))\n                                             (if (#%app pair? datum)\n                                               (let-values (((hx)\n                                                             (#%app car datum))\n                                                            ((hcx)\n                                                             (#%app car datum))\n                                                            ((hpr)\n                                                             (#%app\n                                                              ps-add-car\n                                                              pr))\n                                                            ((tx)\n                                                             (#%app cdr datum))\n                                                            ((tpr)\n                                                             (#%app\n                                                              ps-add-cdr\n                                                              pr)))\n                                                 (let-values (((print13)\n                                                               (#%app\n                                                                datum->syntax\n                                                                hcx\n                                                                hx\n                                                                hcx)))\n                                                   (let-values ()\n                                                     (let-values (((status\n                                                                    result)\n                                                                   (#%app\n                                                                    predicate-ellipsis-parser\n                                                                    tx\n                                                                    cx\n                                                                    tpr\n                                                                    es\n                                                                    expr-stx?\n                                                                    '\"expression\"\n                                                                    '#f)))\n                                                       (let-values (((tmp)\n                                                                     status))\n                                                         (if (#%app\n                                                              equal?\n                                                              tmp\n                                                              'ok)\n                                                           (let-values ()\n                                                             (let-values (((arg15)\n                                                                           result))\n                                                               (let-values ()\n                                                                 (let-values ()\n                                                                   (#%app\n                                                                    t-resyntax\n                                                                    '#f\n                                                                    (quote-syntax\n                                                                     STX)\n                                                                    (#%app\n                                                                     t-list*\n                                                                     (t-quote-syntax\n                                                                      begin)\n                                                                     (let-values (((pv_1)\n                                                                                   arg15))\n                                                                       (#%app\n                                                                        void)\n                                                                       (#%app\n                                                                        map\n                                                                        (lambda (pv_1)\n                                                                          (#%app\n                                                                           t-subst\n                                                                           '#f\n                                                                           (quote-syntax\n                                                                            (display\n                                                                             _))\n                                                                           '(1)\n                                                                           pv_1))\n                                                                        pv_1))))))))\n                                                           (let-values ()\n                                                             (#%app\n                                                              fail-handler9\n                                                              undo-stack10\n                                                              result))))))))\n                                               (let-values (((es*)\n                                                             (if (#%app\n                                                                  null?\n                                                                  datum)\n                                                               (#%app\n                                                                es-add-proper-pair\n                                                                '(any)\n                                                                es)\n                                                               es)))\n                                                 (#%app\n                                                  fail-handler9\n                                                  undo-stack10\n                                                  (#%app\n                                                   failure*\n                                                   pr\n                                                   es*))))))))))))))))))))))))))))\n" (("^[[:space:]]*\\(?:\\(?1:.+?\\)\\):\\(?:\\(?2:[[:digit:]]+\\)\\):\\(?:\\(?3:[[:digit:]]+\\)\\):\\(?:\\(?4:.+\\)\\)$" . error)))
```

Even though I don't think that this call alone should cause any performance problems, I do see several red flags here:

  1. This doesn't look like a list of error messages at all. it is some sourcecode, not supposed to be scanned by racket
  2.  There is only one pattern in the pattern list for errors. No warnings or hints.

Many questions:

 * When will flycheck receive the output with the actual error messages?
 * Are there more processes lauched?
 * How much more garbage output does flycheck have to process?
 * Is the same process output scanned multiple times?

**Comment by sorawee** [comment] 2021-09-01 13:22
> Yes I do disagree, this Answer even annoys me, but I try to explain calmly why this is the case.

I don't see why you should be annoyed. Greg was trying to help you, even though he's not obligated to do so. If anything, I think you should be thankful for his help.

> If the problem is in flycheck wouldn't that mean that all languages would have the same problem?

The problem is actually caused by Flycheck mode itself. Flycheck has two parts: the main framework and checkers for various languages. The problem is in the Racket checker. That's why you don't see it in other languages. See https://github.com/flycheck/flycheck/blob/784f184cdd9f9cb4e3dbb997c09d93e954142842/flycheck.el#L10831 in the Flycheck repo.

You can also verify that this is not Racket Mode's fault by switching to `scheme-mode`, and set (or define, in case you don't have geiser) `geiser-impl--implementation` to `'racket` (flycheck detects a Racket file by looking at major mode and see if it's either `racket-mode` or `scheme-mode` -- for the latter `geiser-impl--implementation` must also be set to `'racket`). Even when the major mode is in `scheme-mode`, I see the same lag.

>     1. This doesn't look like a list of error messages at all. it is some sourcecode, not supposed to be scanned by racket

The way the Racket checker in Flycheck works is that it runs `raco expand <your-file.rkt>`, which prints out expanded code in case there's no syntax error, and prints out error messages in case there's a syntax error. This is obviously not ideal because when there is no error, Flycheck has to process the entire expanded code. Perhaps it should have used `raco make` instead, etc, etc.

**Comment by greghendershott** [comment] 2021-09-01 14:40
@sorawee Oh that's a great point. The fully-expanded syntax even for simple programs can be large; for non-simple programs it can be enormous! Wading through all that is definitely not ideal.

---

It looks like `raco expand` sends the (successful) expansion to `stdout` but the error messages to `stderr`.

So probably `flycheck` wants instead to do something like `raco expand file.rkt >/dev/null`?

(Or the Emacs Lisp equivalent; it's possible to handle stdout and stderr separately with most of the Emacs exec functions. That's more portable than hard-coding a shell-script redirect syntax.)

@krux02 Is that something you'd like to open as an issue or a pull request on the flycheck repo?

**Comment by greghendershott** [comment] 2021-09-01 14:45
Also to confirm what @sorawee said, there is no "integration" going on here between Racket Mode and Flycheck. They are two independent modes that don't need to cooperate and aren't attempting to.

What I was talking about above, with investigating, is seeing if there might be some way in which Racket Mode is inadvertently causing a problem with Flycheck. Setting some variable wrong, or who knows what. I love Emacs, but sometimes the global environment can be a big hairball, but I still love Emacs.

**Closed** 2021-09-01 14:50 UTC
Labels: bug
