### ISSUE TITLE
Syntax-quotes not seen as whole expressions in semantic editing modes

### ISSUE THREAD

**Issue by parenthetical** [greghendershott/racket-mode#135] opened 2015-05-19 15:45 UTC
When using paredit I'd like slurping and barfing to work on the entirety of `#'exp`, ```#`exp``` and `#,exp`.
Currently ```#'``` is seen as one expression and `exp` as another, and slurping these inserts annoying spaces. Commands like `kill-sexp` also have this issue.

**Comment by greghendershott** [comment] 2015-05-19 19:04
I can't reproduce this.

For me, `kill-sexp` and `paredit-{forward,backward}-{slurp,barf}-sexp` all work identically with both:

```
('foo `foo ,foo)
(#'foo #`foo #,foo)
```

I wonder what's different. Could you please <kbd>M-x racket-bug-report</kbd> and paste the output into a comment here?

**Comment by greghendershott** [comment] 2015-05-19 19:07
p.s. If you don't have any `racket-bug-report` command, then the first step would be to please update racket-mode and see if the problem still happens. You probably want to update anyway for the fix to #134. :)

**Comment by parenthetical** [comment] 2015-05-19 19:08
Here it is! Yesterday's racket-mode version.

```
((emacs-version "25.0.50.1")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--source-dir "~/.emacs.d/elpa/racket-mode-20150518.1050/")
 (racket-racket-program "racket")
 (racket-raco-program "raco")
 (racket-memory-limit 512)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-use-company-mode t)
 (racket-check-syntax-mode nil)
 (hs-minor-mode t)
 (dired-omit-mode nil)
 (diff-minor-mode nil)
 (server-buffer-clients nil)
 (edts-mode nil)
 (edts-shell-mode nil)
 (auto-complete-mode nil)
 (buffer-face-mode nil)
 (text-scale-mode nil)
 (eproject-mode t)
 (auto-highlight-symbol-mode nil)
 (xref-etags-mode nil)
 (paredit-mode t)
 (global-whitespace-newline-mode nil)
 (global-whitespace-mode nil)
 (whitespace-newline-mode nil)
 (whitespace-mode nil)
 (highlight-parentheses-mode t)
 (company-search-mode nil)
 (company-mode t)
 (my-keys-minor-mode t)
 (paren-face-mode nil)
 (rectangular-region-mode nil)
 (multiple-cursors-mode nil)
 (helm-mode t)
 (org-cdlatex-mode nil)
 (orgstruct-mode nil)
 (outline-minor-mode nil)
 (semantic-minor-modes-format
  ((:eval
    (if
        (or semantic-highlight-edits-mode semantic-show-unmatched-syntax-mode)
        #(" S" 1 2
          (face bold))))))
 (semantic-highlight-edits-mode nil)
 (semantic-show-unmatched-syntax-mode nil)
 (compilation-minor-mode nil)
 (compilation-shell-minor-mode nil)
 (compilation-in-progress nil)
 (image-minor-mode nil)
 (elm-indentation-mode nil)
 (eldoc-mode nil)
 (visible-mode nil)
 (visual-line-mode t)
 (next-error-follow-minor-mode nil)
 (abbrev-mode nil)
 (overwrite-mode nil)
 (auto-fill-function nil)
 (defining-kbd-macro nil)
 (isearch-mode nil)
```

**Comment by greghendershott** [comment] 2015-05-19 19:25
1. Well, the only difference that really jumps out at me is that you're using Emacs 25.0 whereas I tried this using Emacs 24.3. However it seems unlikely that would matter for something this basic.

2. How about sexpr navigation commands like `forward-sexp` and `backward-sexp`? Do they treat `#;foo` as 1 or 2 things, for you?

**Comment by greghendershott** [comment] 2015-05-19 19:27
@parenthetical If you got my previous comment via email, I fixed a typo after I sent it. I meant `#'foo`.

**Comment by parenthetical** [comment] 2015-05-19 19:32
`forward-sexp` and `backward-sexp` behave as if it were two things.

**Comment by greghendershott** [comment] 2015-05-19 19:51
So that's consistent.

I wonder if [my syntax table entry for `#`](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L75) -- `(modify-syntax-entry ?# "w 14" st)` -- is correct; instead of `w` (word) should it be `'` (prefix)?  Maybe this matters in Emacs 25.0 but not in 24.3.  That seems unlikely but it's my least-worst hypothesis, for now. Looks like I need to try Emacs 25.0.

**Comment by greghendershott** [comment] 2015-05-20 02:55
So I built Emacs 25.0.50.1. Using that, I still can't reproduce this.

I'm stumped. Some things for me to try next:

- Look over the minor modes you have enabled.
- Maybe ask on `#racket` if anyone has experienced this and could they chime in here.

**Comment by greghendershott** [comment] 2015-05-20 03:39
- A couple people on `#racket` said they couldn't reproduce this, either. Although they were happy to tell me about other problems. :)

- I'm just taking wild guesses here, but what does `my-keys-minor-mode` do?

**Comment by parenthetical** [comment] 2015-05-20 12:56
Strange.
`my-keys-minor-mode` doesn't do much besides adding a few key bindings after changing modes, so I don't think that has anything to do with the issue I'm having.

Anything else I could try? It's no big deal to me if I'm the only one having the issue :)

**Comment by greghendershott** [comment] 2015-05-20 21:36
I'm glad it's no big deal to you, because I currently have no idea how to fix this if I can't repro it. :)  But seriously, it bothers me I don't understand _why_ it's behaving differently for you. So I'm not going to shrug and close it.

**Comment by greghendershott** [comment] 2015-05-20 21:43
OK here's an idea. In a racket-mode buffer, do <kbd>C-h v forward-sexp-function</kbd>. If its value is not `nil` for you, what is it?

**Comment by parenthetical** [comment] 2015-05-21 08:44
=forward-sexp-function= is =nil=!

**Comment by greghendershott** [comment] 2015-05-21 15:32
Huh. I'm grasping for straws here, but: What does <kbd>M-x emacs-uptime</kbd> say?

**Comment by parenthetical** [comment] 2015-05-23 14:57
It happens even aften restarting Emacs. It also happens with an empty init file, but not with `emacs -Q` or in `text-mode`. I uninstalled all packages that had anything to do with parens, but that doesn't seem to matter.

So in summary:

Behaviour in `text-mode`:
```
|#'()
;; forward-sexp
#'()|
;; backward-sexp
#|'()
```

Behaviour in `racket-mode`
```
|#'()
;; forward-sexp
#'|()
;; backward-sexp
#|'()
```

**Comment by greghendershott** [comment] 2015-11-12 15:27
I was reviewing open issues. Now I _can_ reproduce this.

The heck.

Changing `#` to have `'` a.k.a. prefix syntax fixes the issue, for me, on Emacs 25.

So far in my testing it does not break anything else. I will probably push a commit with this change, to close this.

**Closed** 2015-11-13 19:34 UTC
Labels: bug
