### ISSUE TITLE
Unable to get completion to work with company-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [greghendershott/racket-mode#224] opened 2016-09-09 15:45 UTC
Hello, 
I'm unable to get `company-mode` working for `racket-mode`. I'm not sure what I'm doing wrong. I only get completions for my own definitions (thanks to 'company-dabbrev-code` backend), but I don't get any completions for any of the keywords in racket.

when i press `C-M-i` on any symbol (other than the ones I defined), I get no completion candidates
Also, I do not get any completions in repl. What am I doing wrong?

**Comment by greghendershott** [comment] 2016-09-09 16:07
First, see [this caveat](https://github.com/greghendershott/racket-mode#completion):

> Tip: When you first visit a .rkt file, or edit it to change its
> `require`s, you may need to `racket-run` it to make the symbols
> available. Otherwise, you may get "stale" symbols, or just those
> from `racket/base`.

Does that help?

---

By the way: For me, when `company-mode` is enabled, I don't need to press <kbd>C-M-i</kbd> -- `company-mode` shows its popup automatically after some initial delay.  So, I'm not sure if you really mean `company-mode` or the vanilla Emacs completion mechanism. But either way I do understand it's not behaving as you expect.

---

Finally, it might be handy if you could <kbd>M-x racket-bug-report</kbd> and paste that info here?

**Comment by CSRaghunandan** [comment] 2016-09-09 16:41
```
((emacs-version "25.1.1")
 (emacs-uptime "1 minute, 1 second")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--source-dir "/Users/csraghunandan/.emacs.d/elpa/racket-mode-20160829.846/")
 (racket-racket-program "racket")
 (racket-raco-program "raco")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (aggressive-indent-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (beacon-mode)
 (blink-cursor-mode)
 (column-number-mode)
 (company-mode)
 (company-quickhelp-mode)
 (delete-selection-mode)
 (display-battery-mode)
 (display-time-mode)
 (electric-indent-mode)
 (erc-autojoin-mode)
 (erc-button-mode)
 (erc-fill-mode)
 (erc-irccontrols-mode)
 (erc-list-mode)
 (erc-match-mode)
 (erc-menu-mode)
 (erc-move-to-prompt-mode)
 (erc-netsplit-mode)
 (erc-networks-mode)
 (erc-noncommands-mode)
 (erc-pcomplete-mode)
 (erc-readonly-mode)
 (erc-ring-mode)
 (erc-stamp-mode)
 (erc-track-mode)
 (file-name-shadow-mode)
 (flyspell-mode)
 (font-lock-mode)
 (global-aggressive-indent-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (golden-ratio-mode)
 (google-this-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-mode)
 (highlight-indent-guides-mode)
 (hs-minor-mode)
 (hungry-delete-mode)
 (line-number-mode)
 (linum-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (prettify-symbols-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (smooth-scrolling-mode)
 (spaceline-helm-mode)
 (spaceline-info-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (visual-line-mode)
 (volatile-highlights-mode)
 (whitespace-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (anaconda-eldoc-mode)
 (anaconda-mode)
 (auto-complete-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (buffer-read-only)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (desktop-save-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (doc-view-minor-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-operator-mode)
 (electric-quote-mode)
 (erc-keep-place-mode)
 (erc-scrolltobottom-mode)
 (erc-smiley-mode)
 (erc-track-minor-mode)
 (erc-unmorse-mode)
 (flycheck-mode)
 (flymake-mode)
 (global-auto-complete-mode)
 (global-company-mode)
 (global-flycheck-mode)
 (global-hungry-delete-mode)
 (global-linum-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (haskell-indentation-mode)
 (helm--minor-mode)
 (helm-adaptive-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (image-minor-mode)
 (intero-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (multiple-cursors-mode)
 (next-error-follow-minor-mode)
 (org-bullets-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (orgstruct-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (projectile-global-mode)
 (projectile-mode)
 (racer-mode)
 (racket-check-syntax-mode)
 (rectangle-mark-mode)
 (save-place-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (temp-buffer-resize-mode)
 (tern-mode)
 (tool-bar-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (w3m-fb-mode)
 (w3m-minor-mode)
 (whitespace-newline-mode)
 (window-divider-mode)
 (winner-mode)
 (xref-etags-mode))
```

**Comment by greghendershott** [comment] 2016-09-09 19:03
Thanks.

I noticed you're using Emacs 25.1.1 and `global-company-mode` -- whereas I tried with 24.5.1 and manual `company-mode`.  So I just re-tried with 25.1.1 RC2 (the 8/29/2016 build) and using `global-company-mode`. However it still works fine for me.  For instance if I type `for` and pause, a company-mode popup appears with various Racket `for` forms.

So unfortunately I can't reproduce this. It works for me.

> EDIT: I am getting completions using complete-symbol command. Is there a manual command to set a company-backend ? I guess company is not able to pick up the racket backend

For awhile now (at least a year?) company-mode has supported using a mode's normal "completion at point function". This is what racket-mode provides, including attaching some special properties for company-mode to use. See [`racket-complete-at-point` definition](https://github.com/greghendershott/racket-mode/blob/master/racket-complete.el#L62-L77) and [setting it as the value of `completion-at-point-functions`](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L244).

company-mode should just find this (I have no special configuration in my Emacs init file for company-mode and racket-mode: it "just works"). Well, its `company-capf` backend should. I thought that's included by default. If you <kbd>C-h v company-backends</kbd> do you see `company-capf` in the list?

**Comment by greghendershott** [comment] 2016-09-09 19:09
Oh wait. It looks like `global-company-mode` is in your list of _disabled_ minor modes.

As a result, you'll need to enable company-mode for specific buffers manually (<kbd>M-x company-mode</kbd>) or do so in your Emacs init file for each mode you want using a hook, in this case `racket-mode-hook`.  I'm not sure how if at all you're using company-mode already with other modes?

**Comment by greghendershott** [comment] 2016-09-09 19:10
Oh wait #2: You do have plain `company-mode` in your list of _enabled_ minor modes so you did have it turned on (by whatever means). Sorry; never mind.

**Comment by CSRaghunandan** [comment] 2016-09-10 02:47
Ah I see where the problem was. I had `company-capf` disabled globally (it was causing problems for some major modes. I've it enabled only for `emacs-lisp-mode`). 

 I enabled `company-capf` mode for `racket-mode` by creating a local variable for `company-backends` and looks like it's working. I guess this is how it's supposed to expand `for` ?? Can you please confirm if this is the case 

<img width="572" alt="screen shot 2016-09-10 at 8 08 43 am" src="https://cloud.githubusercontent.com/assets/5226809/18407438/34d805a6-772e-11e6-91a0-763fcc04f974.png">

But, I've two problems now :- 
1. How do i enable `company-capf` backend just for racket-repl (since i have i not enabled it by default) ?
2. `racket-describe` is invoked automatically for each of the company candidates. How do I disable this? I've `company-quickhelp` and it does the same, and `racket-describe` on every completion SLOWS things down a lot.

**Comment by greghendershott** [comment] 2016-09-10 03:29
>  I guess this is how it's supposed to expand for ?? Can you please confirm if this is the case

Yes, those are the completion candidates I get (and would expect to get).

> 1. How do i enable company-capf backend just for racket-repl (since i have i not enabled it by default) ?
> Edit: What is the name of the major mode for racket repl ? If i can get that, I can enable company-capf backend as a hook.

`racket-repl-mode`

> 2. racket-describe is invoked automatically for each of the company candidates. How do I disable this? I've company-quickhelp and it does the same, and racket-describe on every completion candidate SLOWS things down a lot.

For me, that does not happen automatically -- only if I press <kbd>C-h</kbd>. I'm not familiar with `company-quickhelp`.

**Comment by CSRaghunandan** [comment] 2016-09-10 03:35
I got it to work for `racket-repl-mode`.

> For me, that does not happen automatically -- only if I press C-h. I'm not familiar with company-quickhelp.

That is very strange.. I don't want a documentation popup everytime when i want to select candidates using company. it's annoying and makes things slow. 
Why is this happening and how can i turn it off ? it's making it impossible for my to write any code. (everytime `waiting for racket |` pops up when there is a candidate and it takes long to show up)

**Comment by greghendershott** [comment] 2016-09-10 03:43
I agree, that's annoying.

From what I just read about `company-quickhelp`, it does exactly this; is that correct? Are you saying you believe you've disabled it for `racket-mode` (and `racket-repl-mode`) but the behavior is still happening?

Are you sure `company-quickhelp` is disabled? I ask because I do see `company-quickhelp-mode` in the `enabled-minor-modes` list.  Can you do `(company-quickhelp-mode 0)` in both racket-mode hooks, to disable it?

**Comment by greghendershott** [comment] 2016-09-10 03:46
> I do see `company-quickhelp-mode` in the `enabled-minor-modes` list.

Just to clarify I mean I see it in [the `racket-bug-report` data you'd provided](https://github.com/greghendershott/racket-mode/issues/224#issuecomment-245968847).  Maybe you've disabled it since then, but, I wanted to double-check.

**Comment by CSRaghunandan** [comment] 2016-09-10 03:49
Alright, got it work. disabled quick-help mode. 
Also, i got one final question. sorry for asking so many questions. How do I get `company-dabbrev` to work along with `company-capf` I tried it out and looks like I can have completions from either of them but not both.

**Comment by greghendershott** [comment] 2016-09-10 04:00
> Alright, got it work. disabled quick-help mode.

Yay!

> Also, i got one final question. sorry for asking so many questions. How do I get company-dabbrev to work along with company-capf I tried it out and looks like I can have completions from either of them but not both.

That I don't know. I normally use the bog-standard completions UI in Emacs. Mostly I use `company-mode` only to check compatibility with racket-mode; i.e. situations like right now. :)

I think https://github.com/company-mode/company-mode or http://emacs.stackexchange.com/questions/tagged/company-mode might be places where someone would know more about this?

**Comment by greghendershott** [comment] 2016-09-10 04:04
Maybe http://emacs.stackexchange.com/a/15251/849 ?

**Comment by CSRaghunandan** [comment] 2016-09-10 04:07
> Maybe http://emacs.stackexchange.com/a/15251/849 ? 

Tried that, did not work. 

Looks like `company-capf` and `company-dabbrev` are mutually exclusive ? I don't get how company-mode works

**Comment by CSRaghunandan** [comment] 2016-09-10 04:53
since my main problem is solved, I'll close this issue. thanks for the help.

**Comment by CSRaghunandan** [comment] 2016-09-10 05:03
Got it to work, I add this hook. 
```
  (defun my-racket-mode-hook () 
    (set (make-local-variable 'company-backends)
         '((company-capf company-dabbrev-code)))
    (company-quickhelp-mode 0))
  (add-hook 'racket-mode-hook 'my-racket-mode-hook)
```

**Comment by greghendershott** [comment] 2016-09-10 14:42
You're welcome. I'm happy to hear you got it working.

**Comment by CSRaghunandan** [comment] 2016-09-15 05:06
I seem to have a problem with completions in REPL again. 
Whenever i open a racket file and load it for the first time, the completions work fine in `racket-repl`, but if I open another file and run <kbd>C-c C-k</kbd> to load that file in `racket-repl`, there are no completions for the definitions of the second file. And it's the same if I open a third file and so on. I get completions only for the first file that I loaded.

Also, if I press <kbd>C-M-i</kbd> on any of the definitions of second file, it says `no matches found`

**Comment by greghendershott** [comment] 2016-09-15 13:06
Thanks! As this issue thread was already quite long and turned out to be a configuration question, I'm closing this but I did create a fresh issue for the bug: #225.

**Closed by greghendershott** 2016-09-15 13:06 UTC
Labels: question
