### ISSUE TITLE
Got this error message using racket-describe

### ISSUE THREAD

**Issue by iitalics** [greghendershott/racket-mode#363] opened 2019-02-15 16:04 UTC
```
racket--cmd/await: cache-set!: contract violation
  expected: (or/c promise? syntax?)
  given: #f
  in: the range of
      the 2nd argument of
      (->*
       (path-string? (-> (or/c promise? syntax?)))
       ((or/c #f string?))
       any)
  contract from: (function cache-set!)
  blaming: /home/milo/i/racket/racket-mode/racket/syntax.rkt
   (assuming the contract is correct)
  at: /home/milo/i/racket/racket-mode/racket/syntax.rkt:81.18
```

Sorry for the lack of context, I'll try to reproduce it a bit later but for now I'm going to just leave it here.

**Comment by greghendershott** [comment] 2019-04-03 17:16
Have you seen this happen again? If so, is there any recipe I could try?

I use `racket-describe` very often and I haven't seen this, so I'm not sure where to start.

**Comment by greghendershott** [comment] 2019-04-05 14:43
I mistakenly auto-closed this by using the wrong issue number in a commit.

**Comment by greghendershott** [comment] 2024-02-01 15:18
I'm doing spring cleaning on issues. I'd like to close this because I still haven't had it occur in my own use, no one else has reported this, and I don't have a recipe to reproduce it. If any of those change, I'd be happy to re-open, dig in, and fix.

**Closed by greghendershott** 2024-02-01 15:18 UTC
Labels: cannot-reproduce
