### ISSUE TITLE
Smartparens error in racket mode

### ISSUE THREAD

**Issue by izuo** [greghendershott/racket-mode#200] opened 2016-02-04 10:51 UTC
Hi, I've met a problem while I use ```C-x o```  return from REPL to the racket code buffer.
![smart](https://cloud.githubusercontent.com/assets/8336146/12812848/690c2eb2-cb6f-11e5-821e-61f62b107739.png)
```
((emacs-version "24.5.1")
 (emacs-uptime "2 hours, 4 minutes, 10 seconds")
 (system-type gnu/linux)
 (major-mode racket-repl-mode)
 (racket--source-dir "/home/izuo/.emacs.d/elpa/racket-mode-20160201.1757/")
 (racket-racket-program "racket")
 (racket-raco-program "raco")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (anzu-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (beacon-mode)
 (column-number-mode)
 (company-mode)
 (delete-selection-mode)
 (diff-auto-refine-mode)
 (electric-indent-mode)
 (erc-autojoin-mode)
 (erc-button-mode)
 (erc-fill-mode)
 (erc-irccontrols-mode)
 (erc-list-mode)
 (erc-match-mode)
 (erc-menu-mode)
 (erc-move-to-prompt-mode)
 (erc-netsplit-mode)
 (erc-networks-mode)
 (erc-noncommands-mode)
 (erc-pcomplete-mode)
 (erc-readonly-mode)
 (erc-ring-mode)
 (erc-spelling-mode)
 (erc-stamp-mode)
 (erc-track-mode)
 (erc-truncate-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (font-lock-mode)
 (global-anzu-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-diff-hl-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (global-undo-tree-mode)
 (ido-ubiquitous-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (prelude-global-mode)
 (prelude-mode)
 (projectile-global-mode)
 (projectile-mode)
 (recentf-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (volatile-highlights-mode)
 (which-function-mode)
 (winner-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (diff-hl-dir-mode)
 (diff-hl-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-omit-mode)
 (display-time-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (elisp-slime-nav-mode)
 (erc-autoaway-mode)
 (erc-keep-place-mode)
 (erc-log-mode)
 (erc-notify-mode)
 (erc-scrolltobottom-mode)
 (erc-smiley-mode)
 (erc-track-minor-mode)
 (erc-unmorse-mode)
 (flycheck-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-linum-mode)
 (global-magit-file-mode)
 (global-nlinum-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (global-ycmd-mode)
 (guru-global-mode)
 (guru-mode)
 (hl-line-mode)
 (hs-minor-mode)
 (html-autoview-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (ido-everywhere)
 (ido-ubiquitous-debug-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (js2-highlight-unused-variables-mode)
 (js2-minor-mode)
 (linum-mode)
 (magit-blame-mode)
 (magit-blob-mode)
 (magit-file-mode)
 (magit-popup-help-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (nlinum-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (rainbow-delimiters-mode)
 (rainbow-mode)
 (rectangle-mark-mode)
 (rich-minority-mode)
 (rubocop-mode)
 (server-buffer-clients)
 (server-mode)
 (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (temp-buffer-resize-mode)
 (tern-mode)
 (tool-bar-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (whitespace-mode)
 (whitespace-newline-mode)
 (with-editor-mode)
 (ycmd-mode))
```

**Comment by izuo** [comment] 2016-02-05 09:58
Em...I have resolved this issue by some extra config for smartparens,  Sorry to bother you.

**Comment by greghendershott** [comment] 2016-02-05 16:11
Although I use paredit, I was going to install smart-parens, to check this. I just didn't have time to, yet.

I'm glad you resolved it!

Are the extra smart-paren configs special to racket-mode?  If so, please let me know, I could add some "tips" to the README to help other people.

Or, if it's just general smart-parens config, no worries.

**Comment by izuo** [comment] 2016-02-06 07:19
Since my emacs works with default smartparens config well, I think the extra configs are special for
racket-mode, at least on my machine.

the error is:
```
Error in post-command-hook (sp--pair-overlay-post-command-handler): (wrong-type-argument number-or-marker-p nil)
```
here are the configs:
```emacs-lisp
    (setq sp-show-pair-delay 1)
    (sp-local-pair 'racket-repl-mode "'" nil :actions nil)
    (sp-local-pair 'racket-repl-mode "`" nil :actions nil)
```
And I found this issue still appear occasionally while I run racket in REPL and return to the racket code buffer the second time.

**Comment by greghendershott** [comment] 2016-02-06 17:03
I finally got time to look at this hands-on.

1. It looks like [smartparens added specific support for racket-mode](https://github.com/Fuco1/smartparens/blob/master/smartparens-racket.el) a few months ago. To use put `(require 'smartparens-racket)` in your Emacs init file. I'll add that tip to the README.

2. In my opinion, that `smartparens-racket-el` should do for plain quote what it does for quasiquote. IOW not just `(sp-local-pair "`" nil :actions nil)` but also add `(sp-local-pair "'" nil :actions nil)`. I'll submit a PR for that.

3. Having said all that, I can't seem to repro the problem you're reporting. I enable smartparens-mode in both a racket-mode buffer and a racket-repl-mode-buffer. I use <kbd>C-x o</kbd> to move between the windows multiple times. I don't get any `post-command-hook` error. Is there some step I'm missing?

**Comment by izuo** [comment] 2016-02-07 02:25
These two days I am away from PC and enjoy Chinese Spring Festvial，I will look at it soon，thanks for you great work on racket mode，cheers.🎉

发送自 Outlook Mobile

    _____________________________

**Comment by greghendershott** [comment] 2016-02-14 18:49
Although I was never able to reproduce the bug that you originally reported, this did give me the opportunity to add some tips to the README for both paredit and smartparens. So, thank you again for taking the time to report this!

I don't think there's anything left for me to do, so I'm going to go ahead and close this. However please let me know if you disagree.

**Closed by greghendershott** 2016-02-14 18:49 UTC
Labels: bug, cannot-reproduce, documentation
